// RUN: parse-verilog %s 2>>/dev/null | opt -k 6| FileCheck %s
/* Generated by Yosys 0.33 (git sha1 2584903a060) */
// https://github.com/lsils/SCE-benchmarks/blob/main/MCNC/original/5xp1.v
module top_5xp1_y0 (
    x0,
    x1,
    x2,
    x3,
    x4,
    x5,
    x6,
    y0
);
  input x0;
  wire x0;
  input x1;
  wire x1;
  input x2;
  wire x2;
  input x3;
  wire x3;
  input x4;
  wire x4;
  input x5;
  wire x5;
  input x6;
  wire x6;
  output y0;
  wire y0;
  wire tmp;
  LUT6 #(
      .INIT(64'h00ff07fffe000000)
  ) _1_ (
      .I0(tmp),
      .I1(x1),
      .I2(x0),
      .I3(x5),
      .I4(x6),
      .I5(x4),
      .O (y0)
  );
  LUT2 #(
      .INIT(4'h8)
  ) _2_ (
      .I0(x2),
      .I1(x3),
      .O (tmp)
  );
  // CHECK: (LUT 71784915120685056 x4 x6 x5 x0 x1 (LUT 8 x3 x2))
endmodule
