// RUN: parse-verilog %s 2>>/dev/null | opt -k 6| FileCheck %s
/* Generated by Yosys 0.33 (git sha1 2584903a060) */
// https://github.com/lsils/SCE-benchmarks/blob/main/MCNC/original/5xp1.v
module top_5xp1_y1 (
    x0,
    x1,
    x2,
    x3,
    x4,
    x5,
    x6,
    y1
);
  input x0;
  wire x0;
  input x1;
  wire x1;
  input x2;
  wire x2;
  input x3;
  wire x3;
  input x4;
  wire x4;
  input x5;
  wire x5;
  input x6;
  wire x6;
  output y1;
  wire y1;
  wire tmp0;
  wire tmp1;
  LUT3 #(
      .INIT(8'hc5)
  ) _1_ (
      .I0(tmp0),
      .I1(tmp1),
      .I2(x5),
      .O (y1)
  );
  LUT6 #(
      .INIT(64'h00000f0f00077fff)
  ) _2_ (
      .I0(x3),
      .I1(x2),
      .I2(x4),
      .I3(x1),
      .I4(x6),
      .I5(x0),
      .O (tmp1)
  );
  LUT6 #(
      .INIT(64'h010f0f3f0fff0fff)
  ) _3_ (
      .I0(x3),
      .I1(x2),
      .I2(x6),
      .I3(x4),
      .I4(x1),
      .I5(x0),
      .O (tmp0)
  );
  // CHECK: (LUT 197 x5 (LUT 16557099417599 x0 x6 x1 x4 x2 x3) (LUT 76296482214318079 x0 x1 x4 x6 x2 x3))
endmodule
