// RUN: parse-verilog %s 2>>/dev/null | FileCheck %s
/* Generated by Yosys 0.33 (git sha1 2584903a060) */
// https://github.com/lsils/SCE-benchmarks/blob/main/MCNC/original/5xp1.v
module two_outputs (
    x0,
    x1,
    x2,
    x3,
    x4,
    x5,
    x6,
    y0,
    y1
);
  input x0;
  wire x0;
  input x1;
  wire x1;
  input x2;
  wire x2;
  input x3;
  wire x3;
  input x4;
  wire x4;
  input x5;
  wire x5;
  input x6;
  wire x6;
  output y0;
  wire y0;
  output y1;
  wire y1;
  wire tmp0;
  wire tmp1;
  wire tmp2;
  LUT3 #(
      .INIT(8'h38)
  ) _2_ (
      .I0(tmp0),
      .I1(tmp1),
      .I2(x4),
      .O (y0)
  );
  LUT5 #(
      .INIT(32'hfff80000)
  ) _3_ (
      .I0(x3),
      .I1(x2),
      .I2(x0),
      .I3(x1),
      .I4(x6),
      .O (tmp0)
  );
  LUT6 #(
      .INIT(64'hffffff8000000000)
  ) _4_ (
      .I0(x2),
      .I1(x1),
      .I2(x3),
      .I3(x0),
      .I4(x6),
      .I5(x5),
      .O (tmp1)
  );
  LUT5 #(
      .INIT(32'h000bbbbb)
  ) _5_ (
      .I0(x5),
      .I1(tmp2),
      .I2(x4),
      .I3(tmp0),
      .I4(tmp1),
      .O (y1)
  );
  LUT6 #(
      .INIT(64'h010f0f3f0fff0fff)
  ) _6_ (
      .I0(x3),
      .I1(x2),
      .I2(x6),
      .I3(x4),
      .I4(x1),
      .I5(x0),
      .O (tmp2)
  );
  // CHECK: (BUS (LUT 56 x4 (LUT 18446743523953737728 x5 x6 x0 x3 x1 x2) (LUT 4294443008 x6 x1 x0 x2 x3)) (LUT 768955 (LUT 18446743523953737728 x5 x6 x0 x3 x1 x2) (LUT 4294443008 x6 x1 x0 x2 x3) x4 (LUT 76296482214318079 x0 x1 x4 x6 x2 x3) x5))
endmodule
