/* Generated by Yosys 0.53+39 (git sha1 870b667c3, g++ 11.4.0-1ubuntu1~22.04 -fPIC -O3) */

module uart(prescale, s_axis_tdata, clk, m_axis_tready, rst, rxd, s_axis_tvalid, m_axis_tdata, m_axis_tvalid, rx_busy, rx_frame_error, rx_overrun_error, s_axis_tready, tx_busy, txd);
  wire [1:0] _000_;
  wire _001_;
  wire [1:0] _002_;
  wire _003_;
  wire [1:0] _004_;
  wire _005_;
  wire [1:0] _006_;
  wire _007_;
  wire [1:0] _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire [1:0] _012_;
  wire _013_;
  wire [1:0] _014_;
  wire _015_;
  wire [1:0] _016_;
  wire _017_;
  wire [1:0] _018_;
  wire _019_;
  wire [1:0] _020_;
  wire _021_;
  wire [1:0] _022_;
  wire _023_;
  wire [1:0] _024_;
  wire _025_;
  wire [1:0] _026_;
  wire _027_;
  wire [1:0] _028_;
  wire _029_;
  wire [1:0] _030_;
  wire _031_;
  wire [1:0] _032_;
  wire _033_;
  wire [1:0] _034_;
  wire _035_;
  wire [1:0] _036_;
  wire _037_;
  wire [1:0] _038_;
  wire _039_;
  wire [1:0] _040_;
  wire _041_;
  wire [1:0] _042_;
  wire _043_;
  wire [1:0] _044_;
  wire _045_;
  wire [1:0] _046_;
  wire _047_;
  wire [1:0] _048_;
  wire _049_;
  wire [1:0] _050_;
  wire _051_;
  wire [1:0] _052_;
  wire _053_;
  wire [1:0] _054_;
  wire _055_;
  wire [1:0] _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire [1:0] _064_;
  wire _065_;
  wire [1:0] _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire [1:0] _070_;
  wire _071_;
  wire [1:0] _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire [1:0] _076_;
  wire _077_;
  wire [1:0] _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire [1:0] _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire [1:0] _086_;
  wire _087_;
  wire [1:0] _088_;
  wire _089_;
  wire [1:0] _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire [1:0] _094_;
  wire _095_;
  wire [1:0] _096_;
  wire _097_;
  wire [1:0] _098_;
  wire _099_;
  wire [1:0] _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire [1:0] _104_;
  wire _105_;
  wire [1:0] _106_;
  wire _107_;
  wire [1:0] _108_;
  wire _109_;
  wire [1:0] _110_;
  wire _111_;
  wire [1:0] _112_;
  wire _113_;
  wire [1:0] _114_;
  wire _115_;
  wire [1:0] _116_;
  wire _117_;
  wire [1:0] _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire [1:0] _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire [1:0] _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire _175_;
  wire [1:0] _176_;
  wire _177_;
  wire _178_;
  wire _179_;
  wire _180_;
  wire _181_;
  wire _182_;
  wire _183_;
  wire _184_;
  wire _185_;
  wire _186_;
  wire _187_;
  wire _188_;
  wire _189_;
  wire _190_;
  wire _191_;
  wire _192_;
  wire _193_;
  wire [1:0] _194_;
  wire _195_;
  wire [1:0] _196_;
  wire _197_;
  wire _198_;
  wire _199_;
  wire _200_;
  wire _201_;
  wire _202_;
  wire _203_;
  wire _204_;
  wire _205_;
  wire _206_;
  wire _207_;
  wire _208_;
  wire _209_;
  wire _210_;
  wire _211_;
  wire _212_;
  wire _213_;
  wire [1:0] _214_;
  wire _215_;
  wire _216_;
  wire _217_;
  wire _218_;
  wire _219_;
  wire _220_;
  wire _221_;
  wire _222_;
  wire _223_;
  wire _224_;
  wire _225_;
  wire _226_;
  wire _227_;
  wire _228_;
  wire _229_;
  wire _230_;
  wire _231_;
  wire [1:0] _232_;
  wire _233_;
  wire _234_;
  wire _235_;
  wire [1:0] _236_;
  wire _237_;
  wire _238_;
  wire _239_;
  wire [1:0] _240_;
  wire _241_;
  wire [1:0] _242_;
  wire _243_;
  wire [1:0] _244_;
  wire _245_;
  wire [1:0] _246_;
  wire _247_;
  wire [1:0] _248_;
  wire _249_;
  wire _250_;
  wire _251_;
  wire [1:0] _252_;
  wire _253_;
  wire [1:0] _254_;
  wire _255_;
  wire _256_;
  wire _257_;
  wire _258_;
  wire _259_;
  wire [1:0] _260_;
  wire _261_;
  wire [1:0] _262_;
  wire _263_;
  wire [1:0] _264_;
  wire _265_;
  wire _266_;
  wire _267_;
  wire [1:0] _268_;
  wire _269_;
  wire [1:0] _270_;
  wire _271_;
  wire _272_;
  wire _273_;
  wire [1:0] _274_;
  wire _275_;
  wire _276_;
  wire _277_;
  wire [1:0] _278_;
  wire _279_;
  wire _280_;
  wire _281_;
  wire [1:0] _282_;
  wire _283_;
  wire [1:0] _284_;
  wire _285_;
  wire _286_;
  wire _287_;
  wire [1:0] _288_;
  wire _289_;
  wire _290_;
  wire _291_;
  wire [1:0] _292_;
  wire _293_;
  wire [1:0] _294_;
  wire _295_;
  wire [1:0] _296_;
  wire _297_;
  wire [1:0] _298_;
  wire _299_;
  wire _300_;
  wire _301_;
  wire [1:0] _302_;
  wire _303_;
  wire [1:0] _304_;
  wire _305_;
  wire [1:0] _306_;
  wire _307_;
  wire [1:0] _308_;
  wire _309_;
  wire [1:0] _310_;
  wire _311_;
  wire [1:0] _312_;
  wire _313_;
  wire [1:0] _314_;
  wire _315_;
  wire [1:0] _316_;
  wire _317_;
  wire [1:0] _318_;
  wire _319_;
  wire [1:0] _320_;
  wire _321_;
  wire [1:0] _322_;
  wire _323_;
  wire [1:0] _324_;
  wire _325_;
  wire _326_;
  wire _327_;
  wire _328_;
  wire _329_;
  wire _330_;
  wire _331_;
  wire _332_;
  wire _333_;
  wire _334_;
  wire _335_;
  wire _336_;
  wire _337_;
  wire _338_;
  wire _339_;
  wire _340_;
  wire _341_;
  wire _342_;
  wire _343_;
  wire _344_;
  wire _345_;
  wire _346_;
  wire _347_;
  wire [1:0] _348_;
  wire _349_;
  wire _350_;
  wire _351_;
  wire _352_;
  wire _353_;
  wire _354_;
  wire _355_;
  wire _356_;
  wire _357_;
  wire _358_;
  wire _359_;
  wire _360_;
  wire _361_;
  wire _362_;
  wire _363_;
  wire _364_;
  wire _365_;
  wire _366_;
  wire _367_;
  wire _368_;
  wire _369_;
  wire _370_;
  wire _371_;
  wire _372_;
  wire _373_;
  wire _374_;
  wire _375_;
  wire _376_;
  wire _377_;
  wire _378_;
  wire _379_;
  wire _380_;
  wire _381_;
  wire _382_;
  wire _383_;
  wire _384_;
  wire _385_;
  wire _386_;
  wire _387_;
  wire _388_;
  wire _389_;
  wire [1:0] _390_;
  wire _391_;
  wire _392_;
  wire _393_;
  wire _394_;
  wire _395_;
  wire _396_;
  wire _397_;
  wire _398_;
  wire _399_;
  wire _400_;
  wire _401_;
  wire _402_;
  wire _403_;
  wire _404_;
  wire _405_;
  wire _406_;
  wire _407_;
  wire _408_;
  wire _409_;
  wire _410_;
  wire _411_;
  wire _412_;
  wire _413_;
  wire _414_;
  wire _415_;
  wire _416_;
  wire _417_;
  wire _418_;
  wire _419_;
  wire _420_;
  wire _421_;
  wire _422_;
  wire _423_;
  wire _424_;
  wire _425_;
  wire _426_;
  wire _427_;
  wire _428_;
  wire _429_;
  wire _430_;
  wire _431_;
  wire [1:0] _432_;
  wire _433_;
  wire _434_;
  wire _435_;
  wire _436_;
  wire _437_;
  wire _438_;
  wire _439_;
  wire _440_;
  wire _441_;
  wire _442_;
  wire _443_;
  wire _444_;
  wire _445_;
  wire _446_;
  wire _447_;
  wire _448_;
  wire _449_;
  wire _450_;
  wire _451_;
  wire _452_;
  wire _453_;
  wire _454_;
  wire _455_;
  wire _456_;
  wire _457_;
  wire _458_;
  wire _459_;
  wire _460_;
  wire _461_;
  wire [1:0] _462_;
  wire _463_;
  wire _464_;
  wire _465_;
  wire [1:0] _466_;
  wire _467_;
  wire [1:0] _468_;
  wire _469_;
  wire [1:0] _470_;
  wire _471_;
  wire [1:0] _472_;
  wire _473_;
  wire [1:0] _474_;
  wire _475_;
  wire [1:0] _476_;
  wire _477_;
  wire [1:0] _478_;
  wire _479_;
  wire [1:0] _480_;
  wire _481_;
  wire _482_;
  wire _483_;
  wire [1:0] _484_;
  wire _485_;
  wire [1:0] _486_;
  wire _487_;
  wire [1:0] _488_;
  wire _489_;
  wire [1:0] _490_;
  wire _491_;
  wire _N127;
  wire _N136;
  wire _N137;
  wire _N138;
  wire _N139;
  wire _N140;
  wire _N141;
  wire _N142;
  wire _N143;
  wire _N144;
  wire _N145;
  wire _N146;
  wire _N147;
  wire _N148;
  wire _N149;
  wire _N150;
  wire _N151;
  wire _N193;
  wire _N194;
  wire _N195;
  wire _N208;
  wire _N215;
  wire _N221;
  wire _N240;
  wire _N242;
  wire _N266;
  wire _N269;
  wire _N274;
  wire _N292;
  wire _N298;
  wire _N300;
  wire _N301;
  wire _N302;
  wire _N303;
  wire _N304;
  wire _N305;
  wire _N306;
  wire _N307;
  wire _N308;
  wire _N309;
  wire _N310;
  wire _N311;
  wire _N312;
  wire _N313;
  wire _N314;
  wire _N315;
  wire _N316;
  wire _N318;
  wire _N319;
  wire _N320;
  wire _N321;
  wire _N322;
  wire _N323;
  wire _N324;
  wire _N325;
  wire _N326;
  wire _N327;
  wire _N328;
  wire _N329;
  wire _N330;
  wire _N331;
  wire _N332;
  wire _N333;
  wire _N334;
  wire _N336;
  wire _N338;
  wire _N340;
  wire _N41;
  wire _N51;
  input clk;
  wire clk;
  output [7:0] m_axis_tdata;
  wire [7:0] m_axis_tdata;
  input m_axis_tready;
  wire m_axis_tready;
  output m_axis_tvalid;
  wire m_axis_tvalid;
  wire nt_clk;
  wire [7:0] nt_m_axis_tdata;
  wire nt_m_axis_tready;
  wire nt_m_axis_tready_inv;
  wire nt_m_axis_tvalid;
  wire [15:0] nt_prescale;
  wire nt_rst;
  wire nt_rst_inv;
  wire nt_rx_busy;
  wire nt_rx_frame_error;
  wire nt_rx_overrun_error;
  wire nt_rxd;
  wire [7:0] nt_s_axis_tdata;
  wire nt_s_axis_tready;
  wire nt_s_axis_tvalid;
  wire nt_tx_busy;
  wire nt_txd;
  input [15:0] prescale;
  wire [15:0] prescale;
  input rst;
  wire rst;
  output rx_busy;
  wire rx_busy;
  output rx_frame_error;
  wire rx_frame_error;
  output rx_overrun_error;
  wire rx_overrun_error;
  input rxd;
  wire rxd;
  input [7:0] s_axis_tdata;
  wire [7:0] s_axis_tdata;
  output s_axis_tready;
  wire s_axis_tready;
  input s_axis_tvalid;
  wire s_axis_tvalid;
  output tx_busy;
  wire tx_busy;
  output txd;
  wire txd;
  wire \uart_rx_inst/N10 ;
  wire \uart_rx_inst/N10_inv ;
  wire \uart_rx_inst/N120 ;
  wire \uart_rx_inst/N136 ;
  wire \uart_rx_inst/N145 ;
  wire \uart_rx_inst/N145_1 ;
  wire \uart_rx_inst/N17 ;
  wire \uart_rx_inst/N17_inv ;
  wire \uart_rx_inst/N202 ;
  wire \uart_rx_inst/N204 ;
  wire \uart_rx_inst/N205 ;
  wire \uart_rx_inst/N206 ;
  wire [18:0] \uart_rx_inst/N207 ;
  wire [19:0] \uart_rx_inst/N207_3.b_inv ;
  wire [19:0] \uart_rx_inst/N207_3.co ;
  wire \uart_rx_inst/N21 ;
  wire \uart_rx_inst/N236 ;
  wire \uart_rx_inst/N236_inv ;
  wire \uart_rx_inst/N236_inv_1 ;
  wire \uart_rx_inst/N242 ;
  wire \uart_rx_inst/N243 ;
  wire [3:0] \uart_rx_inst/N244 ;
  wire \uart_rx_inst/N271_inv ;
  wire \uart_rx_inst/N272 ;
  wire \uart_rx_inst/N273 ;
  wire \uart_rx_inst/N274 ;
  wire \uart_rx_inst/N290 ;
  wire \uart_rx_inst/N291 ;
  wire \uart_rx_inst/N301 ;
  wire \uart_rx_inst/N305 ;
  wire \uart_rx_inst/N305_inv ;
  wire [3:0] \uart_rx_inst/N324 ;
  wire \uart_rx_inst/N324[1]_inv ;
  wire \uart_rx_inst/N324[2]_inv ;
  wire \uart_rx_inst/N324[3]_inv ;
  wire \uart_rx_inst/N40 ;
  wire \uart_rx_inst/N7 ;
  wire \uart_rx_inst/_N1 ;
  wire [3:0] \uart_rx_inst/bit_cnt ;
  wire [7:0] \uart_rx_inst/data_reg ;
  wire [18:0] \uart_rx_inst/nb0 ;
  wire [18:0] \uart_rx_inst/prescale_reg ;
  wire \uart_rx_inst/rxd_reg ;
  wire \uart_rx_inst/rxd_reg_inv ;
  wire \uart_tx_inst/N102_1_inv ;
  wire \uart_tx_inst/N107 ;
  wire \uart_tx_inst/N107_1 ;
  wire \uart_tx_inst/N109 ;
  wire \uart_tx_inst/N111 ;
  wire \uart_tx_inst/N124 ;
  wire [18:0] \uart_tx_inst/N125 ;
  wire [18:0] \uart_tx_inst/N125_6.co ;
  wire \uart_tx_inst/N130 ;
  wire \uart_tx_inst/N130_inv ;
  wire [3:0] \uart_tx_inst/N151 ;
  wire \uart_tx_inst/N154 ;
  wire \uart_tx_inst/N154_1 ;
  wire \uart_tx_inst/N167 ;
  wire \uart_tx_inst/N167_2 ;
  wire \uart_tx_inst/N167_4 ;
  wire \uart_tx_inst/N167_5 ;
  wire [8:0] \uart_tx_inst/N168 ;
  wire [3:0] \uart_tx_inst/N175 ;
  wire \uart_tx_inst/N175[1]_inv ;
  wire \uart_tx_inst/N175[2]_inv ;
  wire \uart_tx_inst/N175[3]_inv ;
  wire \uart_tx_inst/N24 ;
  wire \uart_tx_inst/N32 ;
  wire \uart_tx_inst/N6 ;
  wire \uart_tx_inst/N6_inv ;
  wire \uart_tx_inst/N81 ;
  wire \uart_tx_inst/N84 ;
  wire \uart_tx_inst/N84_1 ;
  wire \uart_tx_inst/N91 ;
  wire \uart_tx_inst/N97 ;
  wire [3:0] \uart_tx_inst/bit_cnt ;
  wire [8:0] \uart_tx_inst/data_reg ;
  wire [18:0] \uart_tx_inst/nb1 ;
  wire \uart_tx_inst/nb1[0]_inv ;
  wire [18:0] \uart_tx_inst/prescale_reg ;
  wire \uart_tx_inst/s_axis_tready_reg_inv ;
  wire \uart_tx_inst/s_axis_tvalid_inv ;

  GTP_INBUF #(
    .IOSTANDARD("DEFAULT"),
    .TERM_DDR("ON")
  ) clk_ibuf (
    .I(clk),
    .O(nt_clk)
  );
  GTP_OUTBUF #(
    .DRIVE_STRENGTH("8"),
    .IOSTANDARD("DEFAULT"),
    .SLEW_RATE("SLOW")
  ) \m_axis_tdata_obuf[0]  (
    .I(nt_m_axis_tdata[0]),
    .O(m_axis_tdata[0])
  );
  GTP_OUTBUF #(
    .DRIVE_STRENGTH("8"),
    .IOSTANDARD("DEFAULT"),
    .SLEW_RATE("SLOW")
  ) \m_axis_tdata_obuf[1]  (
    .I(nt_m_axis_tdata[1]),
    .O(m_axis_tdata[1])
  );
  GTP_OUTBUF #(
    .DRIVE_STRENGTH("8"),
    .IOSTANDARD("DEFAULT"),
    .SLEW_RATE("SLOW")
  ) \m_axis_tdata_obuf[2]  (
    .I(nt_m_axis_tdata[2]),
    .O(m_axis_tdata[2])
  );
  GTP_OUTBUF #(
    .DRIVE_STRENGTH("8"),
    .IOSTANDARD("DEFAULT"),
    .SLEW_RATE("SLOW")
  ) \m_axis_tdata_obuf[3]  (
    .I(nt_m_axis_tdata[3]),
    .O(m_axis_tdata[3])
  );
  GTP_OUTBUF #(
    .DRIVE_STRENGTH("8"),
    .IOSTANDARD("DEFAULT"),
    .SLEW_RATE("SLOW")
  ) \m_axis_tdata_obuf[4]  (
    .I(nt_m_axis_tdata[4]),
    .O(m_axis_tdata[4])
  );
  GTP_OUTBUF #(
    .DRIVE_STRENGTH("8"),
    .IOSTANDARD("DEFAULT"),
    .SLEW_RATE("SLOW")
  ) \m_axis_tdata_obuf[5]  (
    .I(nt_m_axis_tdata[5]),
    .O(m_axis_tdata[5])
  );
  GTP_OUTBUF #(
    .DRIVE_STRENGTH("8"),
    .IOSTANDARD("DEFAULT"),
    .SLEW_RATE("SLOW")
  ) \m_axis_tdata_obuf[6]  (
    .I(nt_m_axis_tdata[6]),
    .O(m_axis_tdata[6])
  );
  GTP_OUTBUF #(
    .DRIVE_STRENGTH("8"),
    .IOSTANDARD("DEFAULT"),
    .SLEW_RATE("SLOW")
  ) \m_axis_tdata_obuf[7]  (
    .I(nt_m_axis_tdata[7]),
    .O(m_axis_tdata[7])
  );
  GTP_INBUF #(
    .IOSTANDARD("DEFAULT"),
    .TERM_DDR("ON")
  ) m_axis_tready_ibuf (
    .I(m_axis_tready),
    .O(nt_m_axis_tready)
  );
  \$_NOT_  m_axis_tready_ibuf_inv (
    .A(nt_m_axis_tready),
    .Y(nt_m_axis_tready_inv)
  );
  GTP_OUTBUF #(
    .DRIVE_STRENGTH("8"),
    .IOSTANDARD("DEFAULT"),
    .SLEW_RATE("SLOW")
  ) m_axis_tvalid_obuf (
    .I(nt_m_axis_tvalid),
    .O(m_axis_tvalid)
  );
  GTP_INBUF #(
    .IOSTANDARD("DEFAULT"),
    .TERM_DDR("ON")
  ) \prescale_ibuf[0]  (
    .I(prescale[0]),
    .O(nt_prescale[0])
  );
  GTP_INBUF #(
    .IOSTANDARD("DEFAULT"),
    .TERM_DDR("ON")
  ) \prescale_ibuf[10]  (
    .I(prescale[10]),
    .O(nt_prescale[10])
  );
  GTP_INBUF #(
    .IOSTANDARD("DEFAULT"),
    .TERM_DDR("ON")
  ) \prescale_ibuf[11]  (
    .I(prescale[11]),
    .O(nt_prescale[11])
  );
  GTP_INBUF #(
    .IOSTANDARD("DEFAULT"),
    .TERM_DDR("ON")
  ) \prescale_ibuf[12]  (
    .I(prescale[12]),
    .O(nt_prescale[12])
  );
  GTP_INBUF #(
    .IOSTANDARD("DEFAULT"),
    .TERM_DDR("ON")
  ) \prescale_ibuf[13]  (
    .I(prescale[13]),
    .O(nt_prescale[13])
  );
  GTP_INBUF #(
    .IOSTANDARD("DEFAULT"),
    .TERM_DDR("ON")
  ) \prescale_ibuf[14]  (
    .I(prescale[14]),
    .O(nt_prescale[14])
  );
  GTP_INBUF #(
    .IOSTANDARD("DEFAULT"),
    .TERM_DDR("ON")
  ) \prescale_ibuf[15]  (
    .I(prescale[15]),
    .O(nt_prescale[15])
  );
  GTP_INBUF #(
    .IOSTANDARD("DEFAULT"),
    .TERM_DDR("ON")
  ) \prescale_ibuf[1]  (
    .I(prescale[1]),
    .O(nt_prescale[1])
  );
  GTP_INBUF #(
    .IOSTANDARD("DEFAULT"),
    .TERM_DDR("ON")
  ) \prescale_ibuf[2]  (
    .I(prescale[2]),
    .O(nt_prescale[2])
  );
  GTP_INBUF #(
    .IOSTANDARD("DEFAULT"),
    .TERM_DDR("ON")
  ) \prescale_ibuf[3]  (
    .I(prescale[3]),
    .O(nt_prescale[3])
  );
  GTP_INBUF #(
    .IOSTANDARD("DEFAULT"),
    .TERM_DDR("ON")
  ) \prescale_ibuf[4]  (
    .I(prescale[4]),
    .O(nt_prescale[4])
  );
  GTP_INBUF #(
    .IOSTANDARD("DEFAULT"),
    .TERM_DDR("ON")
  ) \prescale_ibuf[5]  (
    .I(prescale[5]),
    .O(nt_prescale[5])
  );
  GTP_INBUF #(
    .IOSTANDARD("DEFAULT"),
    .TERM_DDR("ON")
  ) \prescale_ibuf[6]  (
    .I(prescale[6]),
    .O(nt_prescale[6])
  );
  GTP_INBUF #(
    .IOSTANDARD("DEFAULT"),
    .TERM_DDR("ON")
  ) \prescale_ibuf[7]  (
    .I(prescale[7]),
    .O(nt_prescale[7])
  );
  GTP_INBUF #(
    .IOSTANDARD("DEFAULT"),
    .TERM_DDR("ON")
  ) \prescale_ibuf[8]  (
    .I(prescale[8]),
    .O(nt_prescale[8])
  );
  GTP_INBUF #(
    .IOSTANDARD("DEFAULT"),
    .TERM_DDR("ON")
  ) \prescale_ibuf[9]  (
    .I(prescale[9]),
    .O(nt_prescale[9])
  );
  GTP_INBUF #(
    .IOSTANDARD("DEFAULT"),
    .TERM_DDR("ON")
  ) rst_ibuf (
    .I(rst),
    .O(nt_rst)
  );
  \$_NOT_  rst_ibuf_inv (
    .A(nt_rst),
    .Y(nt_rst_inv)
  );
  GTP_OUTBUF #(
    .DRIVE_STRENGTH("8"),
    .IOSTANDARD("DEFAULT"),
    .SLEW_RATE("SLOW")
  ) rx_busy_obuf (
    .I(nt_rx_busy),
    .O(rx_busy)
  );
  GTP_OUTBUF #(
    .DRIVE_STRENGTH("8"),
    .IOSTANDARD("DEFAULT"),
    .SLEW_RATE("SLOW")
  ) rx_frame_error_obuf (
    .I(nt_rx_frame_error),
    .O(rx_frame_error)
  );
  GTP_OUTBUF #(
    .DRIVE_STRENGTH("8"),
    .IOSTANDARD("DEFAULT"),
    .SLEW_RATE("SLOW")
  ) rx_overrun_error_obuf (
    .I(nt_rx_overrun_error),
    .O(rx_overrun_error)
  );
  GTP_INBUF #(
    .IOSTANDARD("DEFAULT"),
    .TERM_DDR("ON")
  ) rxd_ibuf (
    .I(rxd),
    .O(nt_rxd)
  );
  GTP_INBUF #(
    .IOSTANDARD("DEFAULT"),
    .TERM_DDR("ON")
  ) \s_axis_tdata_ibuf[0]  (
    .I(s_axis_tdata[0]),
    .O(nt_s_axis_tdata[0])
  );
  GTP_INBUF #(
    .IOSTANDARD("DEFAULT"),
    .TERM_DDR("ON")
  ) \s_axis_tdata_ibuf[1]  (
    .I(s_axis_tdata[1]),
    .O(nt_s_axis_tdata[1])
  );
  GTP_INBUF #(
    .IOSTANDARD("DEFAULT"),
    .TERM_DDR("ON")
  ) \s_axis_tdata_ibuf[2]  (
    .I(s_axis_tdata[2]),
    .O(nt_s_axis_tdata[2])
  );
  GTP_INBUF #(
    .IOSTANDARD("DEFAULT"),
    .TERM_DDR("ON")
  ) \s_axis_tdata_ibuf[3]  (
    .I(s_axis_tdata[3]),
    .O(nt_s_axis_tdata[3])
  );
  GTP_INBUF #(
    .IOSTANDARD("DEFAULT"),
    .TERM_DDR("ON")
  ) \s_axis_tdata_ibuf[4]  (
    .I(s_axis_tdata[4]),
    .O(nt_s_axis_tdata[4])
  );
  GTP_INBUF #(
    .IOSTANDARD("DEFAULT"),
    .TERM_DDR("ON")
  ) \s_axis_tdata_ibuf[5]  (
    .I(s_axis_tdata[5]),
    .O(nt_s_axis_tdata[5])
  );
  GTP_INBUF #(
    .IOSTANDARD("DEFAULT"),
    .TERM_DDR("ON")
  ) \s_axis_tdata_ibuf[6]  (
    .I(s_axis_tdata[6]),
    .O(nt_s_axis_tdata[6])
  );
  GTP_INBUF #(
    .IOSTANDARD("DEFAULT"),
    .TERM_DDR("ON")
  ) \s_axis_tdata_ibuf[7]  (
    .I(s_axis_tdata[7]),
    .O(nt_s_axis_tdata[7])
  );
  GTP_OUTBUF #(
    .DRIVE_STRENGTH("8"),
    .IOSTANDARD("DEFAULT"),
    .SLEW_RATE("SLOW")
  ) s_axis_tready_obuf (
    .I(nt_s_axis_tready),
    .O(s_axis_tready)
  );
  GTP_INBUF #(
    .IOSTANDARD("DEFAULT"),
    .TERM_DDR("ON")
  ) s_axis_tvalid_ibuf (
    .I(s_axis_tvalid),
    .O(nt_s_axis_tvalid)
  );
  GTP_OUTBUF #(
    .DRIVE_STRENGTH("8"),
    .IOSTANDARD("DEFAULT"),
    .SLEW_RATE("SLOW")
  ) tx_busy_obuf (
    .I(nt_tx_busy),
    .O(tx_busy)
  );
  GTP_OUTBUF #(
    .DRIVE_STRENGTH("8"),
    .IOSTANDARD("DEFAULT"),
    .SLEW_RATE("SLOW")
  ) txd_obuf (
    .I(nt_txd),
    .O(txd)
  );
  \$_NOT_  \uart_rx_inst/N10_inv_vname  (
    .A(\uart_rx_inst/N10 ),
    .Y(\uart_rx_inst/N10_inv )
  );
  \$_OR_  \uart_rx_inst/N10_mux18_10  (
    .A(\uart_rx_inst/prescale_reg [14]),
    .B(\uart_rx_inst/prescale_reg [15]),
    .Y(_N326)
  );
  \$_OR_  \uart_rx_inst/N10_mux18_11  (
    .A(\uart_rx_inst/prescale_reg [16]),
    .B(_N326),
    .Y(_N327)
  );
  \$_OR_  \uart_rx_inst/N10_mux18_12  (
    .A(\uart_rx_inst/prescale_reg [17]),
    .B(\uart_rx_inst/prescale_reg [18]),
    .Y(_N328)
  );
  \$_OR_  \uart_rx_inst/N10_mux18_13  (
    .A(\uart_rx_inst/prescale_reg [0]),
    .B(_N328),
    .Y(_N329)
  );
  \$_OR_  \uart_rx_inst/N10_mux18_14  (
    .A(\uart_rx_inst/prescale_reg [1]),
    .B(_N319),
    .Y(_N330)
  );
  \$_OR_  \uart_rx_inst/N10_mux18_15  (
    .A(_N321),
    .B(_N323),
    .Y(_N331)
  );
  \$_OR_  \uart_rx_inst/N10_mux18_16  (
    .A(_N325),
    .B(_N327),
    .Y(_N332)
  );
  \$_OR_  \uart_rx_inst/N10_mux18_17  (
    .A(_N329),
    .B(_N330),
    .Y(_N333)
  );
  \$_OR_  \uart_rx_inst/N10_mux18_18  (
    .A(_N331),
    .B(_N332),
    .Y(_N334)
  );
  \$_OR_  \uart_rx_inst/N10_mux18_19  (
    .A(_N333),
    .B(_N334),
    .Y(\uart_rx_inst/N10 )
  );
  \$_OR_  \uart_rx_inst/N10_mux18_2  (
    .A(\uart_rx_inst/prescale_reg [2]),
    .B(\uart_rx_inst/prescale_reg [3]),
    .Y(_N318)
  );
  \$_OR_  \uart_rx_inst/N10_mux18_3  (
    .A(\uart_rx_inst/prescale_reg [4]),
    .B(_N318),
    .Y(_N319)
  );
  \$_OR_  \uart_rx_inst/N10_mux18_4  (
    .A(\uart_rx_inst/prescale_reg [5]),
    .B(\uart_rx_inst/prescale_reg [6]),
    .Y(_N320)
  );
  \$_OR_  \uart_rx_inst/N10_mux18_5  (
    .A(\uart_rx_inst/prescale_reg [7]),
    .B(_N320),
    .Y(_N321)
  );
  \$_OR_  \uart_rx_inst/N10_mux18_6  (
    .A(\uart_rx_inst/prescale_reg [8]),
    .B(\uart_rx_inst/prescale_reg [9]),
    .Y(_N322)
  );
  \$_OR_  \uart_rx_inst/N10_mux18_7  (
    .A(\uart_rx_inst/prescale_reg [10]),
    .B(_N322),
    .Y(_N323)
  );
  \$_OR_  \uart_rx_inst/N10_mux18_8  (
    .A(\uart_rx_inst/prescale_reg [11]),
    .B(\uart_rx_inst/prescale_reg [12]),
    .Y(_N324)
  );
  \$_OR_  \uart_rx_inst/N10_mux18_9  (
    .A(\uart_rx_inst/prescale_reg [13]),
    .B(_N324),
    .Y(_N325)
  );
  \$_AND_  \uart_rx_inst/N120_1  (
    .A(\uart_rx_inst/bit_cnt [0]),
    .B(_N274),
    .Y(\uart_rx_inst/N120 )
  );
  \$_AND_  \uart_rx_inst/N136_vname  (
    .A(\uart_rx_inst/N120 ),
    .B(\uart_rx_inst/rxd_reg ),
    .Y(\uart_rx_inst/N136 )
  );
  \$_AND_  \uart_rx_inst/N145_vname  (
    .A(\uart_rx_inst/N10_inv ),
    .B(\uart_rx_inst/N136 ),
    .Y(\uart_rx_inst/N145 )
  );
  \$_NOT_  \uart_rx_inst/N17_eq0_inv  (
    .A(\uart_rx_inst/bit_cnt [0]),
    .Y(\uart_rx_inst/N324 [0])
  );
  \$_NOT_  \uart_rx_inst/N17_inv_vname  (
    .A(\uart_rx_inst/N17 ),
    .Y(\uart_rx_inst/N17_inv )
  );
  \$_OR_  \uart_rx_inst/N17_mux1  (
    .A(\uart_rx_inst/bit_cnt [0]),
    .B(\uart_rx_inst/bit_cnt [1]),
    .Y(_N41)
  );
  \$_OR_  \uart_rx_inst/N17_mux3_2  (
    .A(\uart_rx_inst/bit_cnt [2]),
    .B(\uart_rx_inst/bit_cnt [3]),
    .Y(_N336)
  );
  \$_OR_  \uart_rx_inst/N17_mux3_3  (
    .A(_N41),
    .B(_N336),
    .Y(\uart_rx_inst/N17 )
  );
  \$_AND_  \uart_rx_inst/N202_vname  (
    .A(\uart_rx_inst/N17_inv ),
    .B(\uart_rx_inst/rxd_reg_inv ),
    .Y(\uart_rx_inst/N202 )
  );
  \$_AND_  \uart_rx_inst/N204_3  (
    .A(\uart_rx_inst/N10_inv ),
    .B(_N195),
    .Y(\uart_rx_inst/N204 )
  );
  \$_OR_  \uart_rx_inst/N205_vname  (
    .A(nt_rst),
    .B(\uart_rx_inst/N204 ),
    .Y(\uart_rx_inst/N205 )
  );
  \$_OR_  \uart_rx_inst/N206_1  (
    .A(\uart_rx_inst/N10 ),
    .B(\uart_rx_inst/N40 ),
    .Y(_N208)
  );
  \$_AND_  \uart_rx_inst/N206_2  (
    .A(\uart_rx_inst/rxd_reg_inv ),
    .B(_N292),
    .Y(_N242)
  );
  \$_OR_  \uart_rx_inst/N206_3  (
    .A(\uart_rx_inst/N17_inv ),
    .B(\uart_rx_inst/N21 ),
    .Y(_N292)
  );
  \$_OR_  \uart_rx_inst/N206_3_1  (
    .A(nt_rst),
    .B(_N208),
    .Y(\uart_rx_inst/N290 )
  );
  \$_OR_  \uart_rx_inst/N206_5  (
    .A(\uart_rx_inst/N10 ),
    .B(\uart_rx_inst/N17 ),
    .Y(\uart_rx_inst/N236 )
  );
  \$_OR_  \uart_rx_inst/N206_6  (
    .A(_N208),
    .B(_N242),
    .Y(\uart_rx_inst/N206 )
  );
  GTP_LUT6CARRY #(
    .I5_TO_CARRY("FALSE"),
    .I5_TO_LUT("FALSE"),
    .INIT(64'hffffffff00000000)
  ) \uart_rx_inst/N207_3.fsub_0  (
    .COUT(\uart_rx_inst/N207_3.co [0])
  );
  GTP_LUT6CARRY #(
    .I5_TO_CARRY("TRUE"),
    .I5_TO_LUT("FALSE"),
    .INIT(64'hc3c3c3c33c3c3c3c)
  ) \uart_rx_inst/N207_3.fsub_1  (
    .CIN(\uart_rx_inst/N207_3.co [0]),
    .COUT(\uart_rx_inst/N207_3.co [1]),
    .I1(\uart_rx_inst/N207_3.b_inv [0]),
    .I2(\uart_rx_inst/prescale_reg [0]),
    .I5(\uart_rx_inst/prescale_reg [0]),
    .Z(\uart_rx_inst/N207 [0])
  );
  GTP_LUT6CARRY #(
    .I5_TO_CARRY("TRUE"),
    .I5_TO_LUT("FALSE"),
    .INIT(64'haaaaaaaa55555555)
  ) \uart_rx_inst/N207_3.fsub_10  (
    .CIN(\uart_rx_inst/N207_3.co [9]),
    .COUT(\uart_rx_inst/N207_3.co [10]),
    .I0(\uart_rx_inst/nb0 [9]),
    .I5(\uart_rx_inst/nb0 [9]),
    .Z(\uart_rx_inst/N207 [9])
  );
  GTP_LUT6CARRY #(
    .I5_TO_CARRY("TRUE"),
    .I5_TO_LUT("FALSE"),
    .INIT(64'haaaaaaaa55555555)
  ) \uart_rx_inst/N207_3.fsub_11  (
    .CIN(\uart_rx_inst/N207_3.co [10]),
    .COUT(\uart_rx_inst/N207_3.co [11]),
    .I0(\uart_rx_inst/nb0 [10]),
    .I5(\uart_rx_inst/nb0 [10]),
    .Z(\uart_rx_inst/N207 [10])
  );
  GTP_LUT6CARRY #(
    .I5_TO_CARRY("TRUE"),
    .I5_TO_LUT("FALSE"),
    .INIT(64'haaaaaaaa55555555)
  ) \uart_rx_inst/N207_3.fsub_12  (
    .CIN(\uart_rx_inst/N207_3.co [11]),
    .COUT(\uart_rx_inst/N207_3.co [12]),
    .I0(\uart_rx_inst/nb0 [11]),
    .I5(\uart_rx_inst/nb0 [11]),
    .Z(\uart_rx_inst/N207 [11])
  );
  GTP_LUT6CARRY #(
    .I5_TO_CARRY("TRUE"),
    .I5_TO_LUT("FALSE"),
    .INIT(64'haaaaaaaa55555555)
  ) \uart_rx_inst/N207_3.fsub_13  (
    .CIN(\uart_rx_inst/N207_3.co [12]),
    .COUT(\uart_rx_inst/N207_3.co [13]),
    .I0(\uart_rx_inst/nb0 [12]),
    .I5(\uart_rx_inst/nb0 [12]),
    .Z(\uart_rx_inst/N207 [12])
  );
  GTP_LUT6CARRY #(
    .I5_TO_CARRY("TRUE"),
    .I5_TO_LUT("FALSE"),
    .INIT(64'haaaaaaaa55555555)
  ) \uart_rx_inst/N207_3.fsub_14  (
    .CIN(\uart_rx_inst/N207_3.co [13]),
    .COUT(\uart_rx_inst/N207_3.co [14]),
    .I0(\uart_rx_inst/nb0 [13]),
    .I5(\uart_rx_inst/nb0 [13]),
    .Z(\uart_rx_inst/N207 [13])
  );
  GTP_LUT6CARRY #(
    .I5_TO_CARRY("TRUE"),
    .I5_TO_LUT("FALSE"),
    .INIT(64'haaaaaaaa55555555)
  ) \uart_rx_inst/N207_3.fsub_15  (
    .CIN(\uart_rx_inst/N207_3.co [14]),
    .COUT(\uart_rx_inst/N207_3.co [15]),
    .I0(\uart_rx_inst/nb0 [14]),
    .I5(\uart_rx_inst/nb0 [14]),
    .Z(\uart_rx_inst/N207 [14])
  );
  GTP_LUT6CARRY #(
    .I5_TO_CARRY("TRUE"),
    .I5_TO_LUT("FALSE"),
    .INIT(64'haaaaaaaa55555555)
  ) \uart_rx_inst/N207_3.fsub_16  (
    .CIN(\uart_rx_inst/N207_3.co [15]),
    .COUT(\uart_rx_inst/N207_3.co [16]),
    .I0(\uart_rx_inst/nb0 [15]),
    .I5(\uart_rx_inst/nb0 [15]),
    .Z(\uart_rx_inst/N207 [15])
  );
  GTP_LUT6CARRY #(
    .I5_TO_CARRY("TRUE"),
    .I5_TO_LUT("FALSE"),
    .INIT(64'haaaaaaaa55555555)
  ) \uart_rx_inst/N207_3.fsub_17  (
    .CIN(\uart_rx_inst/N207_3.co [16]),
    .COUT(\uart_rx_inst/N207_3.co [17]),
    .I0(\uart_rx_inst/nb0 [16]),
    .I5(\uart_rx_inst/nb0 [16]),
    .Z(\uart_rx_inst/N207 [16])
  );
  GTP_LUT6CARRY #(
    .I5_TO_CARRY("TRUE"),
    .I5_TO_LUT("FALSE"),
    .INIT(64'haaaaaaaa55555555)
  ) \uart_rx_inst/N207_3.fsub_18  (
    .CIN(\uart_rx_inst/N207_3.co [17]),
    .COUT(\uart_rx_inst/N207_3.co [18]),
    .I0(\uart_rx_inst/nb0 [17]),
    .I5(\uart_rx_inst/nb0 [17]),
    .Z(\uart_rx_inst/N207 [17])
  );
  GTP_LUT6CARRY #(
    .I5_TO_CARRY("TRUE"),
    .I5_TO_LUT("FALSE"),
    .INIT(64'haaaaaaaa55555555)
  ) \uart_rx_inst/N207_3.fsub_19  (
    .CIN(\uart_rx_inst/N207_3.co [18]),
    .I0(\uart_rx_inst/nb0 [18]),
    .Z(\uart_rx_inst/N207 [18])
  );
  GTP_LUT6CARRY #(
    .I5_TO_CARRY("TRUE"),
    .I5_TO_LUT("FALSE"),
    .INIT(64'hc3c3c3c33c3c3c3c)
  ) \uart_rx_inst/N207_3.fsub_2  (
    .CIN(\uart_rx_inst/N207_3.co [1]),
    .COUT(\uart_rx_inst/N207_3.co [2]),
    .I1(\uart_rx_inst/N207_3.b_inv [1]),
    .I2(\uart_rx_inst/prescale_reg [1]),
    .I5(\uart_rx_inst/prescale_reg [1]),
    .Z(\uart_rx_inst/N207 [1])
  );
  GTP_LUT6CARRY #(
    .I5_TO_CARRY("TRUE"),
    .I5_TO_LUT("FALSE"),
    .INIT(64'haaaaaaaa55555555)
  ) \uart_rx_inst/N207_3.fsub_3  (
    .CIN(\uart_rx_inst/N207_3.co [2]),
    .COUT(\uart_rx_inst/N207_3.co [3]),
    .I0(\uart_rx_inst/nb0 [2]),
    .I5(\uart_rx_inst/nb0 [2]),
    .Z(\uart_rx_inst/N207 [2])
  );
  GTP_LUT6CARRY #(
    .I5_TO_CARRY("TRUE"),
    .I5_TO_LUT("FALSE"),
    .INIT(64'haaaaaaaa55555555)
  ) \uart_rx_inst/N207_3.fsub_4  (
    .CIN(\uart_rx_inst/N207_3.co [3]),
    .COUT(\uart_rx_inst/N207_3.co [4]),
    .I0(\uart_rx_inst/nb0 [3]),
    .I5(\uart_rx_inst/nb0 [3]),
    .Z(\uart_rx_inst/N207 [3])
  );
  GTP_LUT6CARRY #(
    .I5_TO_CARRY("TRUE"),
    .I5_TO_LUT("FALSE"),
    .INIT(64'haaaaaaaa55555555)
  ) \uart_rx_inst/N207_3.fsub_5  (
    .CIN(\uart_rx_inst/N207_3.co [4]),
    .COUT(\uart_rx_inst/N207_3.co [5]),
    .I0(\uart_rx_inst/nb0 [4]),
    .I5(\uart_rx_inst/nb0 [4]),
    .Z(\uart_rx_inst/N207 [4])
  );
  GTP_LUT6CARRY #(
    .I5_TO_CARRY("TRUE"),
    .I5_TO_LUT("FALSE"),
    .INIT(64'haaaaaaaa55555555)
  ) \uart_rx_inst/N207_3.fsub_6  (
    .CIN(\uart_rx_inst/N207_3.co [5]),
    .COUT(\uart_rx_inst/N207_3.co [6]),
    .I0(\uart_rx_inst/nb0 [5]),
    .I5(\uart_rx_inst/nb0 [5]),
    .Z(\uart_rx_inst/N207 [5])
  );
  GTP_LUT6CARRY #(
    .I5_TO_CARRY("TRUE"),
    .I5_TO_LUT("FALSE"),
    .INIT(64'haaaaaaaa55555555)
  ) \uart_rx_inst/N207_3.fsub_7  (
    .CIN(\uart_rx_inst/N207_3.co [6]),
    .COUT(\uart_rx_inst/N207_3.co [7]),
    .I0(\uart_rx_inst/nb0 [6]),
    .I5(\uart_rx_inst/nb0 [6]),
    .Z(\uart_rx_inst/N207 [6])
  );
  GTP_LUT6CARRY #(
    .I5_TO_CARRY("TRUE"),
    .I5_TO_LUT("FALSE"),
    .INIT(64'haaaaaaaa55555555)
  ) \uart_rx_inst/N207_3.fsub_8  (
    .CIN(\uart_rx_inst/N207_3.co [7]),
    .COUT(\uart_rx_inst/N207_3.co [8]),
    .I0(\uart_rx_inst/nb0 [7]),
    .I5(\uart_rx_inst/nb0 [7]),
    .Z(\uart_rx_inst/N207 [7])
  );
  GTP_LUT6CARRY #(
    .I5_TO_CARRY("TRUE"),
    .I5_TO_LUT("FALSE"),
    .INIT(64'haaaaaaaa55555555)
  ) \uart_rx_inst/N207_3.fsub_9  (
    .CIN(\uart_rx_inst/N207_3.co [8]),
    .COUT(\uart_rx_inst/N207_3.co [9]),
    .I0(\uart_rx_inst/nb0 [8]),
    .I5(\uart_rx_inst/nb0 [8]),
    .Z(\uart_rx_inst/N207 [8])
  );
  \$_NOT_  \uart_rx_inst/N207_3.inv_0  (
    .A(\uart_rx_inst/N207_3.b_inv [0]),
    .Y(\uart_rx_inst/N207_3.b_inv [1])
  );
  \$_MUX_  \uart_rx_inst/N207_5[10]  (
    .A(nt_prescale[9]),
    .B(\uart_rx_inst/prescale_reg [12]),
    .S(\uart_rx_inst/N10 ),
    .Y(_N145)
  );
  \$_MUX_  \uart_rx_inst/N207_5[11]  (
    .A(nt_prescale[10]),
    .B(\uart_rx_inst/prescale_reg [13]),
    .S(\uart_rx_inst/N10 ),
    .Y(_N146)
  );
  \$_MUX_  \uart_rx_inst/N207_5[12]  (
    .A(nt_prescale[11]),
    .B(\uart_rx_inst/prescale_reg [14]),
    .S(\uart_rx_inst/N10 ),
    .Y(_N147)
  );
  \$_MUX_  \uart_rx_inst/N207_5[13]  (
    .A(nt_prescale[12]),
    .B(\uart_rx_inst/prescale_reg [15]),
    .S(\uart_rx_inst/N10 ),
    .Y(_N148)
  );
  \$_MUX_  \uart_rx_inst/N207_5[14]  (
    .A(nt_prescale[13]),
    .B(\uart_rx_inst/prescale_reg [16]),
    .S(\uart_rx_inst/N10 ),
    .Y(_N149)
  );
  \$_MUX_  \uart_rx_inst/N207_5[15]  (
    .A(nt_prescale[14]),
    .B(\uart_rx_inst/prescale_reg [17]),
    .S(\uart_rx_inst/N10 ),
    .Y(_N150)
  );
  \$_MUX_  \uart_rx_inst/N207_5[16]  (
    .A(nt_prescale[15]),
    .B(\uart_rx_inst/prescale_reg [18]),
    .S(\uart_rx_inst/N10 ),
    .Y(_N151)
  );
  \$_MUX_  \uart_rx_inst/N207_5[1]  (
    .A(nt_prescale[0]),
    .B(\uart_rx_inst/prescale_reg [3]),
    .S(\uart_rx_inst/N10 ),
    .Y(_N136)
  );
  \$_MUX_  \uart_rx_inst/N207_5[2]  (
    .A(nt_prescale[1]),
    .B(\uart_rx_inst/prescale_reg [4]),
    .S(\uart_rx_inst/N10 ),
    .Y(_N137)
  );
  \$_MUX_  \uart_rx_inst/N207_5[3]  (
    .A(nt_prescale[2]),
    .B(\uart_rx_inst/prescale_reg [5]),
    .S(\uart_rx_inst/N10 ),
    .Y(_N138)
  );
  \$_MUX_  \uart_rx_inst/N207_5[4]  (
    .A(nt_prescale[3]),
    .B(\uart_rx_inst/prescale_reg [6]),
    .S(\uart_rx_inst/N10 ),
    .Y(_N139)
  );
  \$_MUX_  \uart_rx_inst/N207_5[5]  (
    .A(nt_prescale[4]),
    .B(\uart_rx_inst/prescale_reg [7]),
    .S(\uart_rx_inst/N10 ),
    .Y(_N140)
  );
  \$_MUX_  \uart_rx_inst/N207_5[6]  (
    .A(nt_prescale[5]),
    .B(\uart_rx_inst/prescale_reg [8]),
    .S(\uart_rx_inst/N10 ),
    .Y(_N141)
  );
  \$_MUX_  \uart_rx_inst/N207_5[7]  (
    .A(nt_prescale[6]),
    .B(\uart_rx_inst/prescale_reg [9]),
    .S(\uart_rx_inst/N10 ),
    .Y(_N142)
  );
  \$_MUX_  \uart_rx_inst/N207_5[8]  (
    .A(nt_prescale[7]),
    .B(\uart_rx_inst/prescale_reg [10]),
    .S(\uart_rx_inst/N10 ),
    .Y(_N143)
  );
  \$_MUX_  \uart_rx_inst/N207_5[9]  (
    .A(nt_prescale[8]),
    .B(\uart_rx_inst/prescale_reg [11]),
    .S(\uart_rx_inst/N10 ),
    .Y(_N144)
  );
  \$_MUX_  \uart_rx_inst/N207_7[0]  (
    .A(\uart_rx_inst/prescale_reg [2]),
    .B(nt_prescale[0]),
    .S(\uart_rx_inst/N207_3.b_inv [0]),
    .Y(\uart_rx_inst/nb0 [2])
  );
  \$_MUX_  \uart_rx_inst/N207_7[10]  (
    .A(_N145),
    .B(nt_prescale[10]),
    .S(\uart_rx_inst/N207_3.b_inv [0]),
    .Y(\uart_rx_inst/nb0 [12])
  );
  \$_MUX_  \uart_rx_inst/N207_7[11]  (
    .A(_N146),
    .B(nt_prescale[11]),
    .S(\uart_rx_inst/N207_3.b_inv [0]),
    .Y(\uart_rx_inst/nb0 [13])
  );
  \$_MUX_  \uart_rx_inst/N207_7[12]  (
    .A(_N147),
    .B(nt_prescale[12]),
    .S(\uart_rx_inst/N207_3.b_inv [0]),
    .Y(\uart_rx_inst/nb0 [14])
  );
  \$_MUX_  \uart_rx_inst/N207_7[13]  (
    .A(_N148),
    .B(nt_prescale[13]),
    .S(\uart_rx_inst/N207_3.b_inv [0]),
    .Y(\uart_rx_inst/nb0 [15])
  );
  \$_MUX_  \uart_rx_inst/N207_7[14]  (
    .A(_N149),
    .B(nt_prescale[14]),
    .S(\uart_rx_inst/N207_3.b_inv [0]),
    .Y(\uart_rx_inst/nb0 [16])
  );
  \$_MUX_  \uart_rx_inst/N207_7[15]  (
    .A(_N150),
    .B(nt_prescale[15]),
    .S(\uart_rx_inst/N207_3.b_inv [0]),
    .Y(\uart_rx_inst/nb0 [17])
  );
  \$_AND_  \uart_rx_inst/N207_7[16]  (
    .A(\uart_rx_inst/N207_3.b_inv [1]),
    .B(_N151),
    .Y(\uart_rx_inst/nb0 [18])
  );
  \$_MUX_  \uart_rx_inst/N207_7[1]  (
    .A(_N136),
    .B(nt_prescale[1]),
    .S(\uart_rx_inst/N207_3.b_inv [0]),
    .Y(\uart_rx_inst/nb0 [3])
  );
  \$_MUX_  \uart_rx_inst/N207_7[2]  (
    .A(_N137),
    .B(nt_prescale[2]),
    .S(\uart_rx_inst/N207_3.b_inv [0]),
    .Y(\uart_rx_inst/nb0 [4])
  );
  \$_MUX_  \uart_rx_inst/N207_7[3]  (
    .A(_N138),
    .B(nt_prescale[3]),
    .S(\uart_rx_inst/N207_3.b_inv [0]),
    .Y(\uart_rx_inst/nb0 [5])
  );
  \$_MUX_  \uart_rx_inst/N207_7[4]  (
    .A(_N139),
    .B(nt_prescale[4]),
    .S(\uart_rx_inst/N207_3.b_inv [0]),
    .Y(\uart_rx_inst/nb0 [6])
  );
  \$_MUX_  \uart_rx_inst/N207_7[5]  (
    .A(_N140),
    .B(nt_prescale[5]),
    .S(\uart_rx_inst/N207_3.b_inv [0]),
    .Y(\uart_rx_inst/nb0 [7])
  );
  \$_MUX_  \uart_rx_inst/N207_7[6]  (
    .A(_N141),
    .B(nt_prescale[6]),
    .S(\uart_rx_inst/N207_3.b_inv [0]),
    .Y(\uart_rx_inst/nb0 [8])
  );
  \$_MUX_  \uart_rx_inst/N207_7[7]  (
    .A(_N142),
    .B(nt_prescale[7]),
    .S(\uart_rx_inst/N207_3.b_inv [0]),
    .Y(\uart_rx_inst/nb0 [9])
  );
  \$_MUX_  \uart_rx_inst/N207_7[8]  (
    .A(_N143),
    .B(nt_prescale[8]),
    .S(\uart_rx_inst/N207_3.b_inv [0]),
    .Y(\uart_rx_inst/nb0 [10])
  );
  \$_MUX_  \uart_rx_inst/N207_7[9]  (
    .A(_N144),
    .B(nt_prescale[9]),
    .S(\uart_rx_inst/N207_3.b_inv [0]),
    .Y(\uart_rx_inst/nb0 [11])
  );
  \$_AND_  \uart_rx_inst/N212  (
    .A(\uart_rx_inst/N10_inv ),
    .B(\uart_rx_inst/N202 ),
    .Y(\uart_rx_inst/N207_3.b_inv [0])
  );
  \$_OR_  \uart_rx_inst/N21_mux2  (
    .A(\uart_rx_inst/bit_cnt [1]),
    .B(\uart_rx_inst/bit_cnt [2]),
    .Y(_N51)
  );
  \$_AND_  \uart_rx_inst/N21_mux3  (
    .A(\uart_rx_inst/bit_cnt [3]),
    .B(_N51),
    .Y(\uart_rx_inst/N21 )
  );
  \$_NOT_  \uart_rx_inst/N236_inv_vname  (
    .A(\uart_rx_inst/N236 ),
    .Y(\uart_rx_inst/N236_inv )
  );
  \$_OR_  \uart_rx_inst/N242_1  (
    .A(nt_rst),
    .B(_N193),
    .Y(\uart_rx_inst/N242 )
  );
  \$_AND_  \uart_rx_inst/N242_2  (
    .A(\uart_rx_inst/N10_inv ),
    .B(_N194),
    .Y(_N193)
  );
  \$_OR_  \uart_rx_inst/N242_3  (
    .A(\uart_rx_inst/N120 ),
    .B(_N195),
    .Y(_N194)
  );
  \$_AND_  \uart_rx_inst/N242_4  (
    .A(\uart_rx_inst/N21 ),
    .B(\uart_rx_inst/rxd_reg ),
    .Y(_N195)
  );
  \$_AND_  \uart_rx_inst/N243_1  (
    .A(\uart_rx_inst/N10_inv ),
    .B(_N269),
    .Y(\uart_rx_inst/N243 )
  );
  \$_OR_  \uart_rx_inst/N243_2  (
    .A(\uart_rx_inst/N40 ),
    .B(\uart_rx_inst/N202 ),
    .Y(_N269)
  );
  \$_AND_  \uart_rx_inst/N244_1  (
    .A(\uart_rx_inst/N324 [0]),
    .B(\uart_rx_inst/N207_3.b_inv [1]),
    .Y(\uart_rx_inst/N244 [0])
  );
  \$_AND_  \uart_rx_inst/N244_3  (
    .A(\uart_rx_inst/N324 [2]),
    .B(\uart_rx_inst/N207_3.b_inv [1]),
    .Y(\uart_rx_inst/N244 [2])
  );
  \$_XOR_  \uart_rx_inst/N25_sum1  (
    .A(\uart_rx_inst/bit_cnt [0]),
    .B(\uart_rx_inst/bit_cnt [1]),
    .Y(\uart_rx_inst/N324[1]_inv )
  );
  \$_NOT_  \uart_rx_inst/N25_sum1_inv  (
    .A(\uart_rx_inst/N324[1]_inv ),
    .Y(\uart_rx_inst/N244 [1])
  );
  \$_XOR_  \uart_rx_inst/N25_sum2  (
    .A(\uart_rx_inst/bit_cnt [2]),
    .B(_N41),
    .Y(\uart_rx_inst/N324[2]_inv )
  );
  \$_NOT_  \uart_rx_inst/N25_sum2_inv  (
    .A(\uart_rx_inst/N324[2]_inv ),
    .Y(\uart_rx_inst/N324 [2])
  );
  \$_XOR_  \uart_rx_inst/N25_sum3_1  (
    .A(\uart_rx_inst/bit_cnt [3]),
    .B(_N215),
    .Y(\uart_rx_inst/N324[3]_inv )
  );
  \$_NOT_  \uart_rx_inst/N25_sum3_1_inv  (
    .A(\uart_rx_inst/N324[3]_inv ),
    .Y(\uart_rx_inst/N244 [3])
  );
  \$_OR_  \uart_rx_inst/N25_sum3_2  (
    .A(\uart_rx_inst/bit_cnt [2]),
    .B(_N41),
    .Y(_N215)
  );
  \$_NOT_  \uart_rx_inst/N271_inv_vname  (
    .A(\uart_rx_inst/N136 ),
    .Y(\uart_rx_inst/N271_inv )
  );
  \$_AND_  \uart_rx_inst/N272_vname  (
    .A(\uart_rx_inst/N17 ),
    .B(\uart_rx_inst/N271_inv ),
    .Y(\uart_rx_inst/N272 )
  );
  \$_OR_  \uart_rx_inst/N273_1  (
    .A(\uart_rx_inst/N272 ),
    .B(\uart_rx_inst/N290 ),
    .Y(\uart_rx_inst/N273 )
  );
  \$_AND_  \uart_rx_inst/N274_vname  (
    .A(nt_m_axis_tvalid),
    .B(\uart_rx_inst/N136 ),
    .Y(\uart_rx_inst/N274 )
  );
  \$_AND_  \uart_rx_inst/N291_vname  (
    .A(\uart_rx_inst/N120 ),
    .B(\uart_rx_inst/rxd_reg_inv ),
    .Y(\uart_rx_inst/N291 )
  );
  \$_AND_  \uart_rx_inst/N301_2  (
    .A(nt_rst_inv),
    .B(_N221),
    .Y(_N338)
  );
  \$_XOR_  \uart_rx_inst/N301_3  (
    .A(\uart_rx_inst/bit_cnt [3]),
    .B(_N51),
    .Y(_N221)
  );
  \$_AND_  \uart_rx_inst/N301_4  (
    .A(\uart_rx_inst/N10_inv ),
    .B(_N338),
    .Y(\uart_rx_inst/N301 )
  );
  \$_OR_  \uart_rx_inst/N305_1  (
    .A(nt_rst),
    .B(\uart_rx_inst/N207_3.b_inv [1]),
    .Y(\uart_rx_inst/N305_inv )
  );
  \$_NOT_  \uart_rx_inst/N305_inv_vname  (
    .A(\uart_rx_inst/N305_inv ),
    .Y(\uart_rx_inst/N305 )
  );
  \$_OR_  \uart_rx_inst/N40_mux3  (
    .A(\uart_rx_inst/bit_cnt [3]),
    .B(_N51),
    .Y(\uart_rx_inst/N40 )
  );
  \$_NOT_  \uart_rx_inst/N40_mux3_inv  (
    .A(\uart_rx_inst/N40 ),
    .Y(_N274)
  );
  \$_AND_  \uart_rx_inst/N7_vname  (
    .A(nt_m_axis_tvalid),
    .B(nt_m_axis_tready_inv),
    .Y(\uart_rx_inst/N7 )
  );
  GTP_DFF_RE #(
    .GRS_EN("TRUE"),
    .INIT(1'h0)
  ) \uart_rx_inst/bit_cnt[0]  (
    .CE(\uart_rx_inst/N243 ),
    .CLK(nt_clk),
    .D(\uart_rx_inst/N244 [0]),
    .Q(\uart_rx_inst/bit_cnt [0]),
    .R(\uart_rx_inst/N242 )
  );
  GTP_DFF_RE #(
    .GRS_EN("TRUE"),
    .INIT(1'h0)
  ) \uart_rx_inst/bit_cnt[1]  (
    .CE(\uart_rx_inst/N243 ),
    .CLK(nt_clk),
    .D(\uart_rx_inst/N244 [1]),
    .Q(\uart_rx_inst/bit_cnt [1]),
    .R(\uart_rx_inst/N242 )
  );
  GTP_DFF_RE #(
    .GRS_EN("TRUE"),
    .INIT(1'h0)
  ) \uart_rx_inst/bit_cnt[2]  (
    .CE(\uart_rx_inst/N243 ),
    .CLK(nt_clk),
    .D(\uart_rx_inst/N244 [2]),
    .Q(\uart_rx_inst/bit_cnt [2]),
    .R(\uart_rx_inst/N242 )
  );
  GTP_DFF_RE #(
    .GRS_EN("TRUE"),
    .INIT(1'h0)
  ) \uart_rx_inst/bit_cnt[3]  (
    .CE(\uart_rx_inst/N243 ),
    .CLK(nt_clk),
    .D(\uart_rx_inst/N244 [3]),
    .Q(\uart_rx_inst/bit_cnt [3]),
    .R(\uart_rx_inst/N242 )
  );
  GTP_DFF_RE #(
    .GRS_EN("TRUE"),
    .INIT(1'h0)
  ) \uart_rx_inst/busy_reg  (
    .CE(\uart_rx_inst/N236_inv_1 ),
    .CLK(nt_clk),
    .D(\uart_rx_inst/rxd_reg_inv ),
    .Q(nt_rx_busy),
    .R(nt_rst)
  );
  \$_OR_  \uart_rx_inst/busy_reg_ce_fix  (
    .A(nt_rst),
    .B(\uart_rx_inst/N236_inv ),
    .Y(\uart_rx_inst/N236_inv_1 )
  );
  GTP_DFF_RE #(
    .GRS_EN("TRUE"),
    .INIT(1'h0)
  ) \uart_rx_inst/data_reg[0]  (
    .CE(\uart_rx_inst/N301 ),
    .CLK(nt_clk),
    .D(\uart_rx_inst/data_reg [1]),
    .Q(\uart_rx_inst/data_reg [0]),
    .R(\uart_rx_inst/N305 )
  );
  GTP_DFF_RE #(
    .GRS_EN("TRUE"),
    .INIT(1'h0)
  ) \uart_rx_inst/data_reg[1]  (
    .CE(\uart_rx_inst/N301 ),
    .CLK(nt_clk),
    .D(\uart_rx_inst/data_reg [2]),
    .Q(\uart_rx_inst/data_reg [1]),
    .R(\uart_rx_inst/N305 )
  );
  GTP_DFF_RE #(
    .GRS_EN("TRUE"),
    .INIT(1'h0)
  ) \uart_rx_inst/data_reg[2]  (
    .CE(\uart_rx_inst/N301 ),
    .CLK(nt_clk),
    .D(\uart_rx_inst/data_reg [3]),
    .Q(\uart_rx_inst/data_reg [2]),
    .R(\uart_rx_inst/N305 )
  );
  GTP_DFF_RE #(
    .GRS_EN("TRUE"),
    .INIT(1'h0)
  ) \uart_rx_inst/data_reg[3]  (
    .CE(\uart_rx_inst/N301 ),
    .CLK(nt_clk),
    .D(\uart_rx_inst/data_reg [4]),
    .Q(\uart_rx_inst/data_reg [3]),
    .R(\uart_rx_inst/N305 )
  );
  GTP_DFF_RE #(
    .GRS_EN("TRUE"),
    .INIT(1'h0)
  ) \uart_rx_inst/data_reg[4]  (
    .CE(\uart_rx_inst/N301 ),
    .CLK(nt_clk),
    .D(\uart_rx_inst/data_reg [5]),
    .Q(\uart_rx_inst/data_reg [4]),
    .R(\uart_rx_inst/N305 )
  );
  GTP_DFF_RE #(
    .GRS_EN("TRUE"),
    .INIT(1'h0)
  ) \uart_rx_inst/data_reg[5]  (
    .CE(\uart_rx_inst/N301 ),
    .CLK(nt_clk),
    .D(\uart_rx_inst/data_reg [6]),
    .Q(\uart_rx_inst/data_reg [5]),
    .R(\uart_rx_inst/N305 )
  );
  GTP_DFF_RE #(
    .GRS_EN("TRUE"),
    .INIT(1'h0)
  ) \uart_rx_inst/data_reg[6]  (
    .CE(\uart_rx_inst/N301 ),
    .CLK(nt_clk),
    .D(\uart_rx_inst/data_reg [7]),
    .Q(\uart_rx_inst/data_reg [6]),
    .R(\uart_rx_inst/N305 )
  );
  GTP_DFF_RE #(
    .GRS_EN("TRUE"),
    .INIT(1'h0)
  ) \uart_rx_inst/data_reg[7]  (
    .CE(\uart_rx_inst/N301 ),
    .CLK(nt_clk),
    .D(\uart_rx_inst/rxd_reg ),
    .Q(\uart_rx_inst/data_reg [7]),
    .R(\uart_rx_inst/N305 )
  );
  GTP_DFF_R #(
    .GRS_EN("TRUE"),
    .INIT(1'h0)
  ) \uart_rx_inst/frame_error_reg  (
    .CLK(nt_clk),
    .D(\uart_rx_inst/N291 ),
    .Q(nt_rx_frame_error),
    .R(\uart_rx_inst/N290 )
  );
  GTP_DFF_RE #(
    .GRS_EN("TRUE"),
    .INIT(1'h0)
  ) \uart_rx_inst/m_axis_tdata_reg[0]  (
    .CE(\uart_rx_inst/N145_1 ),
    .CLK(nt_clk),
    .D(\uart_rx_inst/data_reg [0]),
    .Q(nt_m_axis_tdata[0]),
    .R(nt_rst)
  );
  \$_OR_  \uart_rx_inst/m_axis_tdata_reg[0]_ce_fix  (
    .A(nt_rst),
    .B(\uart_rx_inst/N145 ),
    .Y(\uart_rx_inst/N145_1 )
  );
  GTP_DFF_RE #(
    .GRS_EN("TRUE"),
    .INIT(1'h0)
  ) \uart_rx_inst/m_axis_tdata_reg[1]  (
    .CE(\uart_rx_inst/N145_1 ),
    .CLK(nt_clk),
    .D(\uart_rx_inst/data_reg [1]),
    .Q(nt_m_axis_tdata[1]),
    .R(nt_rst)
  );
  GTP_DFF_RE #(
    .GRS_EN("TRUE"),
    .INIT(1'h0)
  ) \uart_rx_inst/m_axis_tdata_reg[2]  (
    .CE(\uart_rx_inst/N145_1 ),
    .CLK(nt_clk),
    .D(\uart_rx_inst/data_reg [2]),
    .Q(nt_m_axis_tdata[2]),
    .R(nt_rst)
  );
  GTP_DFF_RE #(
    .GRS_EN("TRUE"),
    .INIT(1'h0)
  ) \uart_rx_inst/m_axis_tdata_reg[3]  (
    .CE(\uart_rx_inst/N145_1 ),
    .CLK(nt_clk),
    .D(\uart_rx_inst/data_reg [3]),
    .Q(nt_m_axis_tdata[3]),
    .R(nt_rst)
  );
  GTP_DFF_RE #(
    .GRS_EN("TRUE"),
    .INIT(1'h0)
  ) \uart_rx_inst/m_axis_tdata_reg[4]  (
    .CE(\uart_rx_inst/N145_1 ),
    .CLK(nt_clk),
    .D(\uart_rx_inst/data_reg [4]),
    .Q(nt_m_axis_tdata[4]),
    .R(nt_rst)
  );
  GTP_DFF_RE #(
    .GRS_EN("TRUE"),
    .INIT(1'h0)
  ) \uart_rx_inst/m_axis_tdata_reg[5]  (
    .CE(\uart_rx_inst/N145_1 ),
    .CLK(nt_clk),
    .D(\uart_rx_inst/data_reg [5]),
    .Q(nt_m_axis_tdata[5]),
    .R(nt_rst)
  );
  GTP_DFF_RE #(
    .GRS_EN("TRUE"),
    .INIT(1'h0)
  ) \uart_rx_inst/m_axis_tdata_reg[6]  (
    .CE(\uart_rx_inst/N145_1 ),
    .CLK(nt_clk),
    .D(\uart_rx_inst/data_reg [6]),
    .Q(nt_m_axis_tdata[6]),
    .R(nt_rst)
  );
  GTP_DFF_RE #(
    .GRS_EN("TRUE"),
    .INIT(1'h0)
  ) \uart_rx_inst/m_axis_tdata_reg[7]  (
    .CE(\uart_rx_inst/N145_1 ),
    .CLK(nt_clk),
    .D(\uart_rx_inst/data_reg [7]),
    .Q(nt_m_axis_tdata[7]),
    .R(nt_rst)
  );
  GTP_DFF_R #(
    .GRS_EN("TRUE"),
    .INIT(1'h0)
  ) \uart_rx_inst/m_axis_tvalid_reg  (
    .CLK(nt_clk),
    .D(\uart_rx_inst/_N1 ),
    .Q(nt_m_axis_tvalid),
    .R(nt_rst)
  );
  \$_OR_  \uart_rx_inst/m_axis_tvalid_reg_d[0]  (
    .A(\uart_rx_inst/N7 ),
    .B(\uart_rx_inst/N145 ),
    .Y(\uart_rx_inst/_N1 )
  );
  GTP_DFF_R #(
    .GRS_EN("TRUE"),
    .INIT(1'h0)
  ) \uart_rx_inst/overrun_error_reg  (
    .CLK(nt_clk),
    .D(\uart_rx_inst/N274 ),
    .Q(nt_rx_overrun_error),
    .R(\uart_rx_inst/N273 )
  );
  GTP_DFF_RE #(
    .GRS_EN("TRUE"),
    .INIT(1'h0)
  ) \uart_rx_inst/prescale_reg[0]  (
    .CE(\uart_rx_inst/N206 ),
    .CLK(nt_clk),
    .D(\uart_rx_inst/N207 [0]),
    .Q(\uart_rx_inst/prescale_reg [0]),
    .R(\uart_rx_inst/N205 )
  );
  GTP_DFF_RE #(
    .GRS_EN("TRUE"),
    .INIT(1'h0)
  ) \uart_rx_inst/prescale_reg[10]  (
    .CE(\uart_rx_inst/N206 ),
    .CLK(nt_clk),
    .D(\uart_rx_inst/N207 [10]),
    .Q(\uart_rx_inst/prescale_reg [10]),
    .R(\uart_rx_inst/N205 )
  );
  GTP_DFF_RE #(
    .GRS_EN("TRUE"),
    .INIT(1'h0)
  ) \uart_rx_inst/prescale_reg[11]  (
    .CE(\uart_rx_inst/N206 ),
    .CLK(nt_clk),
    .D(\uart_rx_inst/N207 [11]),
    .Q(\uart_rx_inst/prescale_reg [11]),
    .R(\uart_rx_inst/N205 )
  );
  GTP_DFF_RE #(
    .GRS_EN("TRUE"),
    .INIT(1'h0)
  ) \uart_rx_inst/prescale_reg[12]  (
    .CE(\uart_rx_inst/N206 ),
    .CLK(nt_clk),
    .D(\uart_rx_inst/N207 [12]),
    .Q(\uart_rx_inst/prescale_reg [12]),
    .R(\uart_rx_inst/N205 )
  );
  GTP_DFF_RE #(
    .GRS_EN("TRUE"),
    .INIT(1'h0)
  ) \uart_rx_inst/prescale_reg[13]  (
    .CE(\uart_rx_inst/N206 ),
    .CLK(nt_clk),
    .D(\uart_rx_inst/N207 [13]),
    .Q(\uart_rx_inst/prescale_reg [13]),
    .R(\uart_rx_inst/N205 )
  );
  GTP_DFF_RE #(
    .GRS_EN("TRUE"),
    .INIT(1'h0)
  ) \uart_rx_inst/prescale_reg[14]  (
    .CE(\uart_rx_inst/N206 ),
    .CLK(nt_clk),
    .D(\uart_rx_inst/N207 [14]),
    .Q(\uart_rx_inst/prescale_reg [14]),
    .R(\uart_rx_inst/N205 )
  );
  GTP_DFF_RE #(
    .GRS_EN("TRUE"),
    .INIT(1'h0)
  ) \uart_rx_inst/prescale_reg[15]  (
    .CE(\uart_rx_inst/N206 ),
    .CLK(nt_clk),
    .D(\uart_rx_inst/N207 [15]),
    .Q(\uart_rx_inst/prescale_reg [15]),
    .R(\uart_rx_inst/N205 )
  );
  GTP_DFF_RE #(
    .GRS_EN("TRUE"),
    .INIT(1'h0)
  ) \uart_rx_inst/prescale_reg[16]  (
    .CE(\uart_rx_inst/N206 ),
    .CLK(nt_clk),
    .D(\uart_rx_inst/N207 [16]),
    .Q(\uart_rx_inst/prescale_reg [16]),
    .R(\uart_rx_inst/N205 )
  );
  GTP_DFF_RE #(
    .GRS_EN("TRUE"),
    .INIT(1'h0)
  ) \uart_rx_inst/prescale_reg[17]  (
    .CE(\uart_rx_inst/N206 ),
    .CLK(nt_clk),
    .D(\uart_rx_inst/N207 [17]),
    .Q(\uart_rx_inst/prescale_reg [17]),
    .R(\uart_rx_inst/N205 )
  );
  GTP_DFF_RE #(
    .GRS_EN("TRUE"),
    .INIT(1'h0)
  ) \uart_rx_inst/prescale_reg[18]  (
    .CE(\uart_rx_inst/N206 ),
    .CLK(nt_clk),
    .D(\uart_rx_inst/N207 [18]),
    .Q(\uart_rx_inst/prescale_reg [18]),
    .R(\uart_rx_inst/N205 )
  );
  GTP_DFF_RE #(
    .GRS_EN("TRUE"),
    .INIT(1'h0)
  ) \uart_rx_inst/prescale_reg[1]  (
    .CE(\uart_rx_inst/N206 ),
    .CLK(nt_clk),
    .D(\uart_rx_inst/N207 [1]),
    .Q(\uart_rx_inst/prescale_reg [1]),
    .R(\uart_rx_inst/N205 )
  );
  GTP_DFF_RE #(
    .GRS_EN("TRUE"),
    .INIT(1'h0)
  ) \uart_rx_inst/prescale_reg[2]  (
    .CE(\uart_rx_inst/N206 ),
    .CLK(nt_clk),
    .D(\uart_rx_inst/N207 [2]),
    .Q(\uart_rx_inst/prescale_reg [2]),
    .R(\uart_rx_inst/N205 )
  );
  GTP_DFF_RE #(
    .GRS_EN("TRUE"),
    .INIT(1'h0)
  ) \uart_rx_inst/prescale_reg[3]  (
    .CE(\uart_rx_inst/N206 ),
    .CLK(nt_clk),
    .D(\uart_rx_inst/N207 [3]),
    .Q(\uart_rx_inst/prescale_reg [3]),
    .R(\uart_rx_inst/N205 )
  );
  GTP_DFF_RE #(
    .GRS_EN("TRUE"),
    .INIT(1'h0)
  ) \uart_rx_inst/prescale_reg[4]  (
    .CE(\uart_rx_inst/N206 ),
    .CLK(nt_clk),
    .D(\uart_rx_inst/N207 [4]),
    .Q(\uart_rx_inst/prescale_reg [4]),
    .R(\uart_rx_inst/N205 )
  );
  GTP_DFF_RE #(
    .GRS_EN("TRUE"),
    .INIT(1'h0)
  ) \uart_rx_inst/prescale_reg[5]  (
    .CE(\uart_rx_inst/N206 ),
    .CLK(nt_clk),
    .D(\uart_rx_inst/N207 [5]),
    .Q(\uart_rx_inst/prescale_reg [5]),
    .R(\uart_rx_inst/N205 )
  );
  GTP_DFF_RE #(
    .GRS_EN("TRUE"),
    .INIT(1'h0)
  ) \uart_rx_inst/prescale_reg[6]  (
    .CE(\uart_rx_inst/N206 ),
    .CLK(nt_clk),
    .D(\uart_rx_inst/N207 [6]),
    .Q(\uart_rx_inst/prescale_reg [6]),
    .R(\uart_rx_inst/N205 )
  );
  GTP_DFF_RE #(
    .GRS_EN("TRUE"),
    .INIT(1'h0)
  ) \uart_rx_inst/prescale_reg[7]  (
    .CE(\uart_rx_inst/N206 ),
    .CLK(nt_clk),
    .D(\uart_rx_inst/N207 [7]),
    .Q(\uart_rx_inst/prescale_reg [7]),
    .R(\uart_rx_inst/N205 )
  );
  GTP_DFF_RE #(
    .GRS_EN("TRUE"),
    .INIT(1'h0)
  ) \uart_rx_inst/prescale_reg[8]  (
    .CE(\uart_rx_inst/N206 ),
    .CLK(nt_clk),
    .D(\uart_rx_inst/N207 [8]),
    .Q(\uart_rx_inst/prescale_reg [8]),
    .R(\uart_rx_inst/N205 )
  );
  GTP_DFF_RE #(
    .GRS_EN("TRUE"),
    .INIT(1'h0)
  ) \uart_rx_inst/prescale_reg[9]  (
    .CE(\uart_rx_inst/N206 ),
    .CLK(nt_clk),
    .D(\uart_rx_inst/N207 [9]),
    .Q(\uart_rx_inst/prescale_reg [9]),
    .R(\uart_rx_inst/N205 )
  );
  \$_NOT_  \uart_rx_inst/rxd_reg_inv_vname  (
    .A(\uart_rx_inst/rxd_reg ),
    .Y(\uart_rx_inst/rxd_reg_inv )
  );
  GTP_DFF_S #(
    .GRS_EN("TRUE"),
    .INIT(1'h1)
  ) \uart_rx_inst/rxd_reg_vname  (
    .CLK(nt_clk),
    .D(nt_rxd),
    .Q(\uart_rx_inst/rxd_reg ),
    .S(nt_rst)
  );
  \$_NOT_  \uart_tx_inst/N102_1_inv_vname  (
    .A(\uart_tx_inst/N97 ),
    .Y(\uart_tx_inst/N102_1_inv )
  );
  \$_AND_  \uart_tx_inst/N107_1_vname  (
    .A(\uart_tx_inst/N6_inv ),
    .B(\uart_tx_inst/N167_4 ),
    .Y(\uart_tx_inst/N107 )
  );
  \$_OR_  \uart_tx_inst/N109_vname  (
    .A(nt_rst),
    .B(\uart_tx_inst/N130 ),
    .Y(\uart_tx_inst/N109 )
  );
  \$_AND_  \uart_tx_inst/N111_1  (
    .A(\uart_tx_inst/data_reg [0]),
    .B(\uart_tx_inst/N102_1_inv ),
    .Y(\uart_tx_inst/N111 )
  );
  \$_OR_  \uart_tx_inst/N124_1_1  (
    .A(\uart_tx_inst/N6 ),
    .B(_N340),
    .Y(\uart_tx_inst/N124 )
  );
  \$_OR_  \uart_tx_inst/N124_1_2  (
    .A(\uart_tx_inst/N81 ),
    .B(\uart_tx_inst/N167_4 ),
    .Y(_N340)
  );
  \$_AND_  \uart_tx_inst/N125_0[0]_1  (
    .A(\uart_tx_inst/nb1[0]_inv ),
    .B(\uart_tx_inst/N130_inv ),
    .Y(\uart_tx_inst/N125 [0])
  );
  \$_MUX_  \uart_tx_inst/N125_10  (
    .A(nt_prescale[4]),
    .B(\uart_tx_inst/prescale_reg [7]),
    .S(\uart_tx_inst/N6 ),
    .Y(\uart_tx_inst/nb1 [7])
  );
  \$_MUX_  \uart_tx_inst/N125_11  (
    .A(nt_prescale[5]),
    .B(\uart_tx_inst/prescale_reg [8]),
    .S(\uart_tx_inst/N6 ),
    .Y(\uart_tx_inst/nb1 [8])
  );
  \$_MUX_  \uart_tx_inst/N125_12  (
    .A(nt_prescale[6]),
    .B(\uart_tx_inst/prescale_reg [9]),
    .S(\uart_tx_inst/N6 ),
    .Y(\uart_tx_inst/nb1 [9])
  );
  \$_MUX_  \uart_tx_inst/N125_13  (
    .A(nt_prescale[7]),
    .B(\uart_tx_inst/prescale_reg [10]),
    .S(\uart_tx_inst/N6 ),
    .Y(\uart_tx_inst/nb1 [10])
  );
  \$_MUX_  \uart_tx_inst/N125_14  (
    .A(nt_prescale[8]),
    .B(\uart_tx_inst/prescale_reg [11]),
    .S(\uart_tx_inst/N6 ),
    .Y(\uart_tx_inst/nb1 [11])
  );
  \$_MUX_  \uart_tx_inst/N125_15  (
    .A(nt_prescale[9]),
    .B(\uart_tx_inst/prescale_reg [12]),
    .S(\uart_tx_inst/N6 ),
    .Y(\uart_tx_inst/nb1 [12])
  );
  \$_MUX_  \uart_tx_inst/N125_16  (
    .A(nt_prescale[10]),
    .B(\uart_tx_inst/prescale_reg [13]),
    .S(\uart_tx_inst/N6 ),
    .Y(\uart_tx_inst/nb1 [13])
  );
  \$_MUX_  \uart_tx_inst/N125_17  (
    .A(nt_prescale[11]),
    .B(\uart_tx_inst/prescale_reg [14]),
    .S(\uart_tx_inst/N6 ),
    .Y(\uart_tx_inst/nb1 [14])
  );
  \$_MUX_  \uart_tx_inst/N125_18  (
    .A(nt_prescale[12]),
    .B(\uart_tx_inst/prescale_reg [15]),
    .S(\uart_tx_inst/N6 ),
    .Y(\uart_tx_inst/nb1 [15])
  );
  \$_MUX_  \uart_tx_inst/N125_19  (
    .A(nt_prescale[13]),
    .B(\uart_tx_inst/prescale_reg [16]),
    .S(\uart_tx_inst/N6 ),
    .Y(\uart_tx_inst/nb1 [16])
  );
  \$_MUX_  \uart_tx_inst/N125_20  (
    .A(nt_prescale[14]),
    .B(\uart_tx_inst/prescale_reg [17]),
    .S(\uart_tx_inst/N6 ),
    .Y(\uart_tx_inst/nb1 [17])
  );
  \$_MUX_  \uart_tx_inst/N125_21  (
    .A(nt_prescale[15]),
    .B(\uart_tx_inst/prescale_reg [18]),
    .S(\uart_tx_inst/N6 ),
    .Y(\uart_tx_inst/nb1 [18])
  );
  \$_NOT_  \uart_tx_inst/N125_2_inv  (
    .A(\uart_tx_inst/prescale_reg [0]),
    .Y(\uart_tx_inst/nb1[0]_inv )
  );
  \$_MUX_  \uart_tx_inst/N125_6  (
    .A(nt_prescale[0]),
    .B(\uart_tx_inst/prescale_reg [3]),
    .S(\uart_tx_inst/N6 ),
    .Y(\uart_tx_inst/nb1 [3])
  );
  GTP_LUT6CARRY #(
    .I5_TO_CARRY("FALSE"),
    .I5_TO_LUT("FALSE"),
    .INIT(64'h3333333300000000)
  ) \uart_tx_inst/N125_6.fsub_0  (
    .COUT(\uart_tx_inst/N125_6.co [0]),
    .I1(\uart_tx_inst/nb1[0]_inv )
  );
  GTP_LUT6CARRY #(
    .I5_TO_CARRY("TRUE"),
    .I5_TO_LUT("FALSE"),
    .INIT(64'h2222222211111111)
  ) \uart_tx_inst/N125_6.fsub_1  (
    .CIN(\uart_tx_inst/N125_6.co [0]),
    .COUT(\uart_tx_inst/N125_6.co [1]),
    .I0(\uart_tx_inst/prescale_reg [1]),
    .I1(\uart_tx_inst/N130 ),
    .I5(\uart_tx_inst/prescale_reg [1]),
    .Z(\uart_tx_inst/N125 [1])
  );
  GTP_LUT6CARRY #(
    .I5_TO_CARRY("TRUE"),
    .I5_TO_LUT("FALSE"),
    .INIT(64'he2e2e2e2d1d1d1d1)
  ) \uart_tx_inst/N125_6.fsub_10  (
    .CIN(\uart_tx_inst/N125_6.co [9]),
    .COUT(\uart_tx_inst/N125_6.co [10]),
    .I0(\uart_tx_inst/nb1 [10]),
    .I1(\uart_tx_inst/N130 ),
    .I2(nt_prescale[7]),
    .I5(\uart_tx_inst/nb1 [10]),
    .Z(\uart_tx_inst/N125 [10])
  );
  GTP_LUT6CARRY #(
    .I5_TO_CARRY("TRUE"),
    .I5_TO_LUT("FALSE"),
    .INIT(64'he2e2e2e2d1d1d1d1)
  ) \uart_tx_inst/N125_6.fsub_11  (
    .CIN(\uart_tx_inst/N125_6.co [10]),
    .COUT(\uart_tx_inst/N125_6.co [11]),
    .I0(\uart_tx_inst/nb1 [11]),
    .I1(\uart_tx_inst/N130 ),
    .I2(nt_prescale[8]),
    .I5(\uart_tx_inst/nb1 [11]),
    .Z(\uart_tx_inst/N125 [11])
  );
  GTP_LUT6CARRY #(
    .I5_TO_CARRY("TRUE"),
    .I5_TO_LUT("FALSE"),
    .INIT(64'he2e2e2e2d1d1d1d1)
  ) \uart_tx_inst/N125_6.fsub_12  (
    .CIN(\uart_tx_inst/N125_6.co [11]),
    .COUT(\uart_tx_inst/N125_6.co [12]),
    .I0(\uart_tx_inst/nb1 [12]),
    .I1(\uart_tx_inst/N130 ),
    .I2(nt_prescale[9]),
    .I5(\uart_tx_inst/nb1 [12]),
    .Z(\uart_tx_inst/N125 [12])
  );
  GTP_LUT6CARRY #(
    .I5_TO_CARRY("TRUE"),
    .I5_TO_LUT("FALSE"),
    .INIT(64'he2e2e2e2d1d1d1d1)
  ) \uart_tx_inst/N125_6.fsub_13  (
    .CIN(\uart_tx_inst/N125_6.co [12]),
    .COUT(\uart_tx_inst/N125_6.co [13]),
    .I0(\uart_tx_inst/nb1 [13]),
    .I1(\uart_tx_inst/N130 ),
    .I2(nt_prescale[10]),
    .I5(\uart_tx_inst/nb1 [13]),
    .Z(\uart_tx_inst/N125 [13])
  );
  GTP_LUT6CARRY #(
    .I5_TO_CARRY("TRUE"),
    .I5_TO_LUT("FALSE"),
    .INIT(64'he2e2e2e2d1d1d1d1)
  ) \uart_tx_inst/N125_6.fsub_14  (
    .CIN(\uart_tx_inst/N125_6.co [13]),
    .COUT(\uart_tx_inst/N125_6.co [14]),
    .I0(\uart_tx_inst/nb1 [14]),
    .I1(\uart_tx_inst/N130 ),
    .I2(nt_prescale[11]),
    .I5(\uart_tx_inst/nb1 [14]),
    .Z(\uart_tx_inst/N125 [14])
  );
  GTP_LUT6CARRY #(
    .I5_TO_CARRY("TRUE"),
    .I5_TO_LUT("FALSE"),
    .INIT(64'he2e2e2e2d1d1d1d1)
  ) \uart_tx_inst/N125_6.fsub_15  (
    .CIN(\uart_tx_inst/N125_6.co [14]),
    .COUT(\uart_tx_inst/N125_6.co [15]),
    .I0(\uart_tx_inst/nb1 [15]),
    .I1(\uart_tx_inst/N130 ),
    .I2(nt_prescale[12]),
    .I5(\uart_tx_inst/nb1 [15]),
    .Z(\uart_tx_inst/N125 [15])
  );
  GTP_LUT6CARRY #(
    .I5_TO_CARRY("TRUE"),
    .I5_TO_LUT("FALSE"),
    .INIT(64'he2e2e2e2d1d1d1d1)
  ) \uart_tx_inst/N125_6.fsub_16  (
    .CIN(\uart_tx_inst/N125_6.co [15]),
    .COUT(\uart_tx_inst/N125_6.co [16]),
    .I0(\uart_tx_inst/nb1 [16]),
    .I1(\uart_tx_inst/N130 ),
    .I2(nt_prescale[13]),
    .I5(\uart_tx_inst/nb1 [16]),
    .Z(\uart_tx_inst/N125 [16])
  );
  GTP_LUT6CARRY #(
    .I5_TO_CARRY("TRUE"),
    .I5_TO_LUT("FALSE"),
    .INIT(64'he2e2e2e2d1d1d1d1)
  ) \uart_tx_inst/N125_6.fsub_17  (
    .CIN(\uart_tx_inst/N125_6.co [16]),
    .COUT(\uart_tx_inst/N125_6.co [17]),
    .I0(\uart_tx_inst/nb1 [17]),
    .I1(\uart_tx_inst/N130 ),
    .I2(nt_prescale[14]),
    .I5(\uart_tx_inst/nb1 [17]),
    .Z(\uart_tx_inst/N125 [17])
  );
  GTP_LUT6CARRY #(
    .I5_TO_CARRY("TRUE"),
    .I5_TO_LUT("FALSE"),
    .INIT(64'he2e2e2e2d1d1d1d1)
  ) \uart_tx_inst/N125_6.fsub_18  (
    .CIN(\uart_tx_inst/N125_6.co [17]),
    .I0(\uart_tx_inst/nb1 [18]),
    .I1(\uart_tx_inst/N130 ),
    .I2(nt_prescale[15]),
    .Z(\uart_tx_inst/N125 [18])
  );
  GTP_LUT6CARRY #(
    .I5_TO_CARRY("TRUE"),
    .I5_TO_LUT("FALSE"),
    .INIT(64'h2222222211111111)
  ) \uart_tx_inst/N125_6.fsub_2  (
    .CIN(\uart_tx_inst/N125_6.co [1]),
    .COUT(\uart_tx_inst/N125_6.co [2]),
    .I0(\uart_tx_inst/prescale_reg [2]),
    .I1(\uart_tx_inst/N130 ),
    .I5(\uart_tx_inst/prescale_reg [2]),
    .Z(\uart_tx_inst/N125 [2])
  );
  GTP_LUT6CARRY #(
    .I5_TO_CARRY("TRUE"),
    .I5_TO_LUT("FALSE"),
    .INIT(64'he2e2e2e2d1d1d1d1)
  ) \uart_tx_inst/N125_6.fsub_3  (
    .CIN(\uart_tx_inst/N125_6.co [2]),
    .COUT(\uart_tx_inst/N125_6.co [3]),
    .I0(\uart_tx_inst/nb1 [3]),
    .I1(\uart_tx_inst/N130 ),
    .I2(nt_prescale[0]),
    .I5(\uart_tx_inst/nb1 [3]),
    .Z(\uart_tx_inst/N125 [3])
  );
  GTP_LUT6CARRY #(
    .I5_TO_CARRY("TRUE"),
    .I5_TO_LUT("FALSE"),
    .INIT(64'he2e2e2e2d1d1d1d1)
  ) \uart_tx_inst/N125_6.fsub_4  (
    .CIN(\uart_tx_inst/N125_6.co [3]),
    .COUT(\uart_tx_inst/N125_6.co [4]),
    .I0(\uart_tx_inst/nb1 [4]),
    .I1(\uart_tx_inst/N130 ),
    .I2(nt_prescale[1]),
    .I5(\uart_tx_inst/nb1 [4]),
    .Z(\uart_tx_inst/N125 [4])
  );
  GTP_LUT6CARRY #(
    .I5_TO_CARRY("TRUE"),
    .I5_TO_LUT("FALSE"),
    .INIT(64'he2e2e2e2d1d1d1d1)
  ) \uart_tx_inst/N125_6.fsub_5  (
    .CIN(\uart_tx_inst/N125_6.co [4]),
    .COUT(\uart_tx_inst/N125_6.co [5]),
    .I0(\uart_tx_inst/nb1 [5]),
    .I1(\uart_tx_inst/N130 ),
    .I2(nt_prescale[2]),
    .I5(\uart_tx_inst/nb1 [5]),
    .Z(\uart_tx_inst/N125 [5])
  );
  GTP_LUT6CARRY #(
    .I5_TO_CARRY("TRUE"),
    .I5_TO_LUT("FALSE"),
    .INIT(64'he2e2e2e2d1d1d1d1)
  ) \uart_tx_inst/N125_6.fsub_6  (
    .CIN(\uart_tx_inst/N125_6.co [5]),
    .COUT(\uart_tx_inst/N125_6.co [6]),
    .I0(\uart_tx_inst/nb1 [6]),
    .I1(\uart_tx_inst/N130 ),
    .I2(nt_prescale[3]),
    .I5(\uart_tx_inst/nb1 [6]),
    .Z(\uart_tx_inst/N125 [6])
  );
  GTP_LUT6CARRY #(
    .I5_TO_CARRY("TRUE"),
    .I5_TO_LUT("FALSE"),
    .INIT(64'he2e2e2e2d1d1d1d1)
  ) \uart_tx_inst/N125_6.fsub_7  (
    .CIN(\uart_tx_inst/N125_6.co [6]),
    .COUT(\uart_tx_inst/N125_6.co [7]),
    .I0(\uart_tx_inst/nb1 [7]),
    .I1(\uart_tx_inst/N130 ),
    .I2(nt_prescale[4]),
    .I5(\uart_tx_inst/nb1 [7]),
    .Z(\uart_tx_inst/N125 [7])
  );
  GTP_LUT6CARRY #(
    .I5_TO_CARRY("TRUE"),
    .I5_TO_LUT("FALSE"),
    .INIT(64'he2e2e2e2d1d1d1d1)
  ) \uart_tx_inst/N125_6.fsub_8  (
    .CIN(\uart_tx_inst/N125_6.co [7]),
    .COUT(\uart_tx_inst/N125_6.co [8]),
    .I0(\uart_tx_inst/nb1 [8]),
    .I1(\uart_tx_inst/N130 ),
    .I2(nt_prescale[5]),
    .I5(\uart_tx_inst/nb1 [8]),
    .Z(\uart_tx_inst/N125 [8])
  );
  GTP_LUT6CARRY #(
    .I5_TO_CARRY("TRUE"),
    .I5_TO_LUT("FALSE"),
    .INIT(64'he2e2e2e2d1d1d1d1)
  ) \uart_tx_inst/N125_6.fsub_9  (
    .CIN(\uart_tx_inst/N125_6.co [8]),
    .COUT(\uart_tx_inst/N125_6.co [9]),
    .I0(\uart_tx_inst/nb1 [9]),
    .I1(\uart_tx_inst/N130 ),
    .I2(nt_prescale[6]),
    .I5(\uart_tx_inst/nb1 [9]),
    .Z(\uart_tx_inst/N125 [9])
  );
  \$_MUX_  \uart_tx_inst/N125_7  (
    .A(nt_prescale[1]),
    .B(\uart_tx_inst/prescale_reg [4]),
    .S(\uart_tx_inst/N6 ),
    .Y(\uart_tx_inst/nb1 [4])
  );
  \$_MUX_  \uart_tx_inst/N125_8  (
    .A(nt_prescale[2]),
    .B(\uart_tx_inst/prescale_reg [5]),
    .S(\uart_tx_inst/N6 ),
    .Y(\uart_tx_inst/nb1 [5])
  );
  \$_MUX_  \uart_tx_inst/N125_9  (
    .A(nt_prescale[3]),
    .B(\uart_tx_inst/prescale_reg [6]),
    .S(\uart_tx_inst/N6 ),
    .Y(\uart_tx_inst/nb1 [6])
  );
  \$_NOT_  \uart_tx_inst/N130_inv_vname  (
    .A(\uart_tx_inst/N130 ),
    .Y(\uart_tx_inst/N130_inv )
  );
  \$_AND_  \uart_tx_inst/N130_vname  (
    .A(\uart_tx_inst/N6_inv ),
    .B(\uart_tx_inst/N81 ),
    .Y(\uart_tx_inst/N130 )
  );
  \$_MUX_  \uart_tx_inst/N151_10  (
    .A(\uart_tx_inst/data_reg [6]),
    .B(nt_s_axis_tdata[5]),
    .S(\uart_tx_inst/N97 ),
    .Y(\uart_tx_inst/N168 [5])
  );
  \$_MUX_  \uart_tx_inst/N151_11  (
    .A(\uart_tx_inst/data_reg [7]),
    .B(nt_s_axis_tdata[6]),
    .S(\uart_tx_inst/N97 ),
    .Y(\uart_tx_inst/N168 [6])
  );
  \$_MUX_  \uart_tx_inst/N151_12  (
    .A(\uart_tx_inst/data_reg [8]),
    .B(nt_s_axis_tdata[7]),
    .S(\uart_tx_inst/N97 ),
    .Y(\uart_tx_inst/N168 [7])
  );
  \$_AND_  \uart_tx_inst/N151_2  (
    .A(\uart_tx_inst/N175 [1]),
    .B(\uart_tx_inst/N102_1_inv ),
    .Y(\uart_tx_inst/N151 [1])
  );
  \$_AND_  \uart_tx_inst/N151_3  (
    .A(\uart_tx_inst/N175 [2]),
    .B(\uart_tx_inst/N102_1_inv ),
    .Y(\uart_tx_inst/N151 [2])
  );
  \$_MUX_  \uart_tx_inst/N151_5  (
    .A(\uart_tx_inst/data_reg [1]),
    .B(nt_s_axis_tdata[0]),
    .S(\uart_tx_inst/N97 ),
    .Y(\uart_tx_inst/N168 [0])
  );
  \$_MUX_  \uart_tx_inst/N151_6  (
    .A(\uart_tx_inst/data_reg [2]),
    .B(nt_s_axis_tdata[1]),
    .S(\uart_tx_inst/N97 ),
    .Y(\uart_tx_inst/N168 [1])
  );
  \$_MUX_  \uart_tx_inst/N151_7  (
    .A(\uart_tx_inst/data_reg [3]),
    .B(nt_s_axis_tdata[2]),
    .S(\uart_tx_inst/N97 ),
    .Y(\uart_tx_inst/N168 [2])
  );
  \$_MUX_  \uart_tx_inst/N151_8  (
    .A(\uart_tx_inst/data_reg [4]),
    .B(nt_s_axis_tdata[3]),
    .S(\uart_tx_inst/N97 ),
    .Y(\uart_tx_inst/N168 [3])
  );
  \$_MUX_  \uart_tx_inst/N151_9  (
    .A(\uart_tx_inst/data_reg [5]),
    .B(nt_s_axis_tdata[4]),
    .S(\uart_tx_inst/N97 ),
    .Y(\uart_tx_inst/N168 [4])
  );
  \$_AND_  \uart_tx_inst/N154_vname  (
    .A(\uart_tx_inst/N6_inv ),
    .B(\uart_tx_inst/N84 ),
    .Y(\uart_tx_inst/N154 )
  );
  \$_OR_  \uart_tx_inst/N167_1  (
    .A(\uart_tx_inst/N91 ),
    .B(\uart_tx_inst/N167_5 ),
    .Y(\uart_tx_inst/N167_2 )
  );
  \$_NOT_  \uart_tx_inst/N167_2_inv  (
    .A(\uart_tx_inst/N167_2 ),
    .Y(\uart_tx_inst/N167 )
  );
  \$_OR_  \uart_tx_inst/N167_2_vname  (
    .A(\uart_tx_inst/N32 ),
    .B(\uart_tx_inst/N97 ),
    .Y(\uart_tx_inst/N167_4 )
  );
  \$_NOT_  \uart_tx_inst/N167_4_inv  (
    .A(\uart_tx_inst/N167_4 ),
    .Y(\uart_tx_inst/N167_5 )
  );
  \$_OR_  \uart_tx_inst/N24_vname  (
    .A(\uart_tx_inst/s_axis_tready_reg_inv ),
    .B(\uart_tx_inst/s_axis_tvalid_inv ),
    .Y(\uart_tx_inst/N24 )
  );
  \$_NOT_  \uart_tx_inst/N32_eq0_inv  (
    .A(\uart_tx_inst/bit_cnt [0]),
    .Y(\uart_tx_inst/N175 [0])
  );
  \$_NOT_  \uart_tx_inst/N32_mux3_1_inv  (
    .A(\uart_tx_inst/N32 ),
    .Y(_N266)
  );
  \$_OR_  \uart_tx_inst/N32_mux3_2  (
    .A(\uart_tx_inst/bit_cnt [1]),
    .B(\uart_tx_inst/bit_cnt [3]),
    .Y(_N298)
  );
  \$_OR_  \uart_tx_inst/N32_mux3_3  (
    .A(\uart_tx_inst/bit_cnt [2]),
    .B(_N298),
    .Y(\uart_tx_inst/N32 )
  );
  \$_OR_  \uart_tx_inst/N36_maj1_1  (
    .A(\uart_tx_inst/bit_cnt [0]),
    .B(\uart_tx_inst/bit_cnt [1]),
    .Y(_N127)
  );
  \$_XOR_  \uart_tx_inst/N36_sum1  (
    .A(\uart_tx_inst/bit_cnt [0]),
    .B(\uart_tx_inst/bit_cnt [1]),
    .Y(\uart_tx_inst/N175[1]_inv )
  );
  \$_NOT_  \uart_tx_inst/N36_sum1_inv  (
    .A(\uart_tx_inst/N175[1]_inv ),
    .Y(\uart_tx_inst/N175 [1])
  );
  \$_XOR_  \uart_tx_inst/N36_sum2  (
    .A(\uart_tx_inst/bit_cnt [2]),
    .B(_N127),
    .Y(\uart_tx_inst/N175[2]_inv )
  );
  \$_NOT_  \uart_tx_inst/N36_sum2_inv  (
    .A(\uart_tx_inst/N175[2]_inv ),
    .Y(\uart_tx_inst/N175 [2])
  );
  \$_XOR_  \uart_tx_inst/N36_sum3_1  (
    .A(\uart_tx_inst/bit_cnt [3]),
    .B(_N240),
    .Y(\uart_tx_inst/N175[3]_inv )
  );
  \$_NOT_  \uart_tx_inst/N36_sum3_1_inv  (
    .A(\uart_tx_inst/N175[3]_inv ),
    .Y(\uart_tx_inst/N151 [3])
  );
  \$_OR_  \uart_tx_inst/N36_sum3_2  (
    .A(\uart_tx_inst/bit_cnt [2]),
    .B(_N127),
    .Y(_N240)
  );
  \$_NOT_  \uart_tx_inst/N6_inv_vname  (
    .A(\uart_tx_inst/N6 ),
    .Y(\uart_tx_inst/N6_inv )
  );
  \$_OR_  \uart_tx_inst/N6_mux18_10  (
    .A(\uart_tx_inst/prescale_reg [15]),
    .B(\uart_tx_inst/prescale_reg [16]),
    .Y(_N308)
  );
  \$_OR_  \uart_tx_inst/N6_mux18_11  (
    .A(\uart_tx_inst/prescale_reg [17]),
    .B(_N308),
    .Y(_N309)
  );
  \$_OR_  \uart_tx_inst/N6_mux18_12  (
    .A(\uart_tx_inst/prescale_reg [0]),
    .B(\uart_tx_inst/prescale_reg [18]),
    .Y(_N310)
  );
  \$_OR_  \uart_tx_inst/N6_mux18_13  (
    .A(\uart_tx_inst/prescale_reg [1]),
    .B(_N310),
    .Y(_N311)
  );
  \$_OR_  \uart_tx_inst/N6_mux18_14  (
    .A(\uart_tx_inst/prescale_reg [2]),
    .B(_N301),
    .Y(_N312)
  );
  \$_OR_  \uart_tx_inst/N6_mux18_15  (
    .A(_N303),
    .B(_N305),
    .Y(_N313)
  );
  \$_OR_  \uart_tx_inst/N6_mux18_16  (
    .A(_N307),
    .B(_N309),
    .Y(_N314)
  );
  \$_OR_  \uart_tx_inst/N6_mux18_17  (
    .A(_N311),
    .B(_N312),
    .Y(_N315)
  );
  \$_OR_  \uart_tx_inst/N6_mux18_18  (
    .A(_N313),
    .B(_N314),
    .Y(_N316)
  );
  \$_OR_  \uart_tx_inst/N6_mux18_19  (
    .A(_N315),
    .B(_N316),
    .Y(\uart_tx_inst/N6 )
  );
  \$_OR_  \uart_tx_inst/N6_mux18_2  (
    .A(\uart_tx_inst/prescale_reg [3]),
    .B(\uart_tx_inst/prescale_reg [4]),
    .Y(_N300)
  );
  \$_OR_  \uart_tx_inst/N6_mux18_3  (
    .A(\uart_tx_inst/prescale_reg [5]),
    .B(_N300),
    .Y(_N301)
  );
  \$_OR_  \uart_tx_inst/N6_mux18_4  (
    .A(\uart_tx_inst/prescale_reg [6]),
    .B(\uart_tx_inst/prescale_reg [7]),
    .Y(_N302)
  );
  \$_OR_  \uart_tx_inst/N6_mux18_5  (
    .A(\uart_tx_inst/prescale_reg [8]),
    .B(_N302),
    .Y(_N303)
  );
  \$_OR_  \uart_tx_inst/N6_mux18_6  (
    .A(\uart_tx_inst/prescale_reg [9]),
    .B(\uart_tx_inst/prescale_reg [10]),
    .Y(_N304)
  );
  \$_OR_  \uart_tx_inst/N6_mux18_7  (
    .A(\uart_tx_inst/prescale_reg [11]),
    .B(_N304),
    .Y(_N305)
  );
  \$_OR_  \uart_tx_inst/N6_mux18_8  (
    .A(\uart_tx_inst/prescale_reg [12]),
    .B(\uart_tx_inst/prescale_reg [13]),
    .Y(_N306)
  );
  \$_OR_  \uart_tx_inst/N6_mux18_9  (
    .A(\uart_tx_inst/prescale_reg [14]),
    .B(_N306),
    .Y(_N307)
  );
  \$_AND_  \uart_tx_inst/N81_vname  (
    .A(\uart_tx_inst/bit_cnt [0]),
    .B(_N266),
    .Y(\uart_tx_inst/N81 )
  );
  \$_AND_  \uart_tx_inst/N84_vname  (
    .A(\uart_tx_inst/N175 [0]),
    .B(_N266),
    .Y(\uart_tx_inst/N84 )
  );
  \$_OR_  \uart_tx_inst/N91_vname  (
    .A(nt_rst),
    .B(\uart_tx_inst/N6 ),
    .Y(\uart_tx_inst/N91 )
  );
  \$_AND_  \uart_tx_inst/N97_vname  (
    .A(nt_s_axis_tvalid),
    .B(\uart_tx_inst/N84 ),
    .Y(\uart_tx_inst/N97 )
  );
  GTP_DFF_RE #(
    .GRS_EN("TRUE"),
    .INIT(1'h0)
  ) \uart_tx_inst/bit_cnt[0]  (
    .CE(\uart_tx_inst/N107 ),
    .CLK(nt_clk),
    .D(\uart_tx_inst/N175 [0]),
    .Q(\uart_tx_inst/bit_cnt [0]),
    .R(\uart_tx_inst/N109 )
  );
  GTP_DFF_RE #(
    .GRS_EN("TRUE"),
    .INIT(1'h0)
  ) \uart_tx_inst/bit_cnt[1]  (
    .CE(\uart_tx_inst/N107 ),
    .CLK(nt_clk),
    .D(\uart_tx_inst/N151 [1]),
    .Q(\uart_tx_inst/bit_cnt [1]),
    .R(\uart_tx_inst/N109 )
  );
  GTP_DFF_RE #(
    .GRS_EN("TRUE"),
    .INIT(1'h0)
  ) \uart_tx_inst/bit_cnt[2]  (
    .CE(\uart_tx_inst/N107 ),
    .CLK(nt_clk),
    .D(\uart_tx_inst/N151 [2]),
    .Q(\uart_tx_inst/bit_cnt [2]),
    .R(\uart_tx_inst/N109 )
  );
  GTP_DFF_RE #(
    .GRS_EN("TRUE"),
    .INIT(1'h0)
  ) \uart_tx_inst/bit_cnt[3]  (
    .CE(\uart_tx_inst/N107 ),
    .CLK(nt_clk),
    .D(\uart_tx_inst/N151 [3]),
    .Q(\uart_tx_inst/bit_cnt [3]),
    .R(\uart_tx_inst/N109 )
  );
  GTP_DFF_RE #(
    .GRS_EN("TRUE"),
    .INIT(1'h0)
  ) \uart_tx_inst/busy_reg  (
    .CE(\uart_tx_inst/N154_1 ),
    .CLK(nt_clk),
    .D(nt_s_axis_tvalid),
    .Q(nt_tx_busy),
    .R(nt_rst)
  );
  \$_OR_  \uart_tx_inst/busy_reg_ce_fix  (
    .A(nt_rst),
    .B(\uart_tx_inst/N154 ),
    .Y(\uart_tx_inst/N154_1 )
  );
  GTP_DFF_E #(
    .GRS_EN("TRUE"),
    .INIT(1'h0)
  ) \uart_tx_inst/data_reg[0]  (
    .CE(\uart_tx_inst/N167 ),
    .CLK(nt_clk),
    .D(\uart_tx_inst/N168 [0]),
    .Q(\uart_tx_inst/data_reg [0])
  );
  GTP_DFF_E #(
    .GRS_EN("TRUE"),
    .INIT(1'h0)
  ) \uart_tx_inst/data_reg[1]  (
    .CE(\uart_tx_inst/N167 ),
    .CLK(nt_clk),
    .D(\uart_tx_inst/N168 [1]),
    .Q(\uart_tx_inst/data_reg [1])
  );
  GTP_DFF_E #(
    .GRS_EN("TRUE"),
    .INIT(1'h0)
  ) \uart_tx_inst/data_reg[2]  (
    .CE(\uart_tx_inst/N167 ),
    .CLK(nt_clk),
    .D(\uart_tx_inst/N168 [2]),
    .Q(\uart_tx_inst/data_reg [2])
  );
  GTP_DFF_E #(
    .GRS_EN("TRUE"),
    .INIT(1'h0)
  ) \uart_tx_inst/data_reg[3]  (
    .CE(\uart_tx_inst/N167 ),
    .CLK(nt_clk),
    .D(\uart_tx_inst/N168 [3]),
    .Q(\uart_tx_inst/data_reg [3])
  );
  GTP_DFF_E #(
    .GRS_EN("TRUE"),
    .INIT(1'h0)
  ) \uart_tx_inst/data_reg[4]  (
    .CE(\uart_tx_inst/N167 ),
    .CLK(nt_clk),
    .D(\uart_tx_inst/N168 [4]),
    .Q(\uart_tx_inst/data_reg [4])
  );
  GTP_DFF_E #(
    .GRS_EN("TRUE"),
    .INIT(1'h0)
  ) \uart_tx_inst/data_reg[5]  (
    .CE(\uart_tx_inst/N167 ),
    .CLK(nt_clk),
    .D(\uart_tx_inst/N168 [5]),
    .Q(\uart_tx_inst/data_reg [5])
  );
  GTP_DFF_E #(
    .GRS_EN("TRUE"),
    .INIT(1'h0)
  ) \uart_tx_inst/data_reg[6]  (
    .CE(\uart_tx_inst/N167 ),
    .CLK(nt_clk),
    .D(\uart_tx_inst/N168 [6]),
    .Q(\uart_tx_inst/data_reg [6])
  );
  GTP_DFF_E #(
    .GRS_EN("TRUE"),
    .INIT(1'h0)
  ) \uart_tx_inst/data_reg[7]  (
    .CE(\uart_tx_inst/N167 ),
    .CLK(nt_clk),
    .D(\uart_tx_inst/N168 [7]),
    .Q(\uart_tx_inst/data_reg [7])
  );
  GTP_DFF_E #(
    .GRS_EN("TRUE"),
    .INIT(1'h0)
  ) \uart_tx_inst/data_reg[8]  (
    .CE(\uart_tx_inst/N167 ),
    .CLK(nt_clk),
    .D(\uart_tx_inst/N97 ),
    .Q(\uart_tx_inst/data_reg [8])
  );
  GTP_DFF_RE #(
    .GRS_EN("TRUE"),
    .INIT(1'h0)
  ) \uart_tx_inst/prescale_reg[0]  (
    .CE(\uart_tx_inst/N124 ),
    .CLK(nt_clk),
    .D(\uart_tx_inst/N125 [0]),
    .Q(\uart_tx_inst/prescale_reg [0]),
    .R(nt_rst)
  );
  GTP_DFF_RE #(
    .GRS_EN("TRUE"),
    .INIT(1'h0)
  ) \uart_tx_inst/prescale_reg[10]  (
    .CE(\uart_tx_inst/N124 ),
    .CLK(nt_clk),
    .D(\uart_tx_inst/N125 [10]),
    .Q(\uart_tx_inst/prescale_reg [10]),
    .R(nt_rst)
  );
  GTP_DFF_RE #(
    .GRS_EN("TRUE"),
    .INIT(1'h0)
  ) \uart_tx_inst/prescale_reg[11]  (
    .CE(\uart_tx_inst/N124 ),
    .CLK(nt_clk),
    .D(\uart_tx_inst/N125 [11]),
    .Q(\uart_tx_inst/prescale_reg [11]),
    .R(nt_rst)
  );
  GTP_DFF_RE #(
    .GRS_EN("TRUE"),
    .INIT(1'h0)
  ) \uart_tx_inst/prescale_reg[12]  (
    .CE(\uart_tx_inst/N124 ),
    .CLK(nt_clk),
    .D(\uart_tx_inst/N125 [12]),
    .Q(\uart_tx_inst/prescale_reg [12]),
    .R(nt_rst)
  );
  GTP_DFF_RE #(
    .GRS_EN("TRUE"),
    .INIT(1'h0)
  ) \uart_tx_inst/prescale_reg[13]  (
    .CE(\uart_tx_inst/N124 ),
    .CLK(nt_clk),
    .D(\uart_tx_inst/N125 [13]),
    .Q(\uart_tx_inst/prescale_reg [13]),
    .R(nt_rst)
  );
  GTP_DFF_RE #(
    .GRS_EN("TRUE"),
    .INIT(1'h0)
  ) \uart_tx_inst/prescale_reg[14]  (
    .CE(\uart_tx_inst/N124 ),
    .CLK(nt_clk),
    .D(\uart_tx_inst/N125 [14]),
    .Q(\uart_tx_inst/prescale_reg [14]),
    .R(nt_rst)
  );
  GTP_DFF_RE #(
    .GRS_EN("TRUE"),
    .INIT(1'h0)
  ) \uart_tx_inst/prescale_reg[15]  (
    .CE(\uart_tx_inst/N124 ),
    .CLK(nt_clk),
    .D(\uart_tx_inst/N125 [15]),
    .Q(\uart_tx_inst/prescale_reg [15]),
    .R(nt_rst)
  );
  GTP_DFF_RE #(
    .GRS_EN("TRUE"),
    .INIT(1'h0)
  ) \uart_tx_inst/prescale_reg[16]  (
    .CE(\uart_tx_inst/N124 ),
    .CLK(nt_clk),
    .D(\uart_tx_inst/N125 [16]),
    .Q(\uart_tx_inst/prescale_reg [16]),
    .R(nt_rst)
  );
  GTP_DFF_RE #(
    .GRS_EN("TRUE"),
    .INIT(1'h0)
  ) \uart_tx_inst/prescale_reg[17]  (
    .CE(\uart_tx_inst/N124 ),
    .CLK(nt_clk),
    .D(\uart_tx_inst/N125 [17]),
    .Q(\uart_tx_inst/prescale_reg [17]),
    .R(nt_rst)
  );
  GTP_DFF_RE #(
    .GRS_EN("TRUE"),
    .INIT(1'h0)
  ) \uart_tx_inst/prescale_reg[18]  (
    .CE(\uart_tx_inst/N124 ),
    .CLK(nt_clk),
    .D(\uart_tx_inst/N125 [18]),
    .Q(\uart_tx_inst/prescale_reg [18]),
    .R(nt_rst)
  );
  GTP_DFF_RE #(
    .GRS_EN("TRUE"),
    .INIT(1'h0)
  ) \uart_tx_inst/prescale_reg[1]  (
    .CE(\uart_tx_inst/N124 ),
    .CLK(nt_clk),
    .D(\uart_tx_inst/N125 [1]),
    .Q(\uart_tx_inst/prescale_reg [1]),
    .R(nt_rst)
  );
  GTP_DFF_RE #(
    .GRS_EN("TRUE"),
    .INIT(1'h0)
  ) \uart_tx_inst/prescale_reg[2]  (
    .CE(\uart_tx_inst/N124 ),
    .CLK(nt_clk),
    .D(\uart_tx_inst/N125 [2]),
    .Q(\uart_tx_inst/prescale_reg [2]),
    .R(nt_rst)
  );
  GTP_DFF_RE #(
    .GRS_EN("TRUE"),
    .INIT(1'h0)
  ) \uart_tx_inst/prescale_reg[3]  (
    .CE(\uart_tx_inst/N124 ),
    .CLK(nt_clk),
    .D(\uart_tx_inst/N125 [3]),
    .Q(\uart_tx_inst/prescale_reg [3]),
    .R(nt_rst)
  );
  GTP_DFF_RE #(
    .GRS_EN("TRUE"),
    .INIT(1'h0)
  ) \uart_tx_inst/prescale_reg[4]  (
    .CE(\uart_tx_inst/N124 ),
    .CLK(nt_clk),
    .D(\uart_tx_inst/N125 [4]),
    .Q(\uart_tx_inst/prescale_reg [4]),
    .R(nt_rst)
  );
  GTP_DFF_RE #(
    .GRS_EN("TRUE"),
    .INIT(1'h0)
  ) \uart_tx_inst/prescale_reg[5]  (
    .CE(\uart_tx_inst/N124 ),
    .CLK(nt_clk),
    .D(\uart_tx_inst/N125 [5]),
    .Q(\uart_tx_inst/prescale_reg [5]),
    .R(nt_rst)
  );
  GTP_DFF_RE #(
    .GRS_EN("TRUE"),
    .INIT(1'h0)
  ) \uart_tx_inst/prescale_reg[6]  (
    .CE(\uart_tx_inst/N124 ),
    .CLK(nt_clk),
    .D(\uart_tx_inst/N125 [6]),
    .Q(\uart_tx_inst/prescale_reg [6]),
    .R(nt_rst)
  );
  GTP_DFF_RE #(
    .GRS_EN("TRUE"),
    .INIT(1'h0)
  ) \uart_tx_inst/prescale_reg[7]  (
    .CE(\uart_tx_inst/N124 ),
    .CLK(nt_clk),
    .D(\uart_tx_inst/N125 [7]),
    .Q(\uart_tx_inst/prescale_reg [7]),
    .R(nt_rst)
  );
  GTP_DFF_RE #(
    .GRS_EN("TRUE"),
    .INIT(1'h0)
  ) \uart_tx_inst/prescale_reg[8]  (
    .CE(\uart_tx_inst/N124 ),
    .CLK(nt_clk),
    .D(\uart_tx_inst/N125 [8]),
    .Q(\uart_tx_inst/prescale_reg [8]),
    .R(nt_rst)
  );
  GTP_DFF_RE #(
    .GRS_EN("TRUE"),
    .INIT(1'h0)
  ) \uart_tx_inst/prescale_reg[9]  (
    .CE(\uart_tx_inst/N124 ),
    .CLK(nt_clk),
    .D(\uart_tx_inst/N125 [9]),
    .Q(\uart_tx_inst/prescale_reg [9]),
    .R(nt_rst)
  );
  GTP_DFF_RE #(
    .GRS_EN("TRUE"),
    .INIT(1'h0)
  ) \uart_tx_inst/s_axis_tready_reg  (
    .CE(\uart_tx_inst/N84_1 ),
    .CLK(nt_clk),
    .D(\uart_tx_inst/N24 ),
    .Q(nt_s_axis_tready),
    .R(\uart_tx_inst/N91 )
  );
  \$_OR_  \uart_tx_inst/s_axis_tready_reg_ce_fix  (
    .A(\uart_tx_inst/N84 ),
    .B(\uart_tx_inst/N91 ),
    .Y(\uart_tx_inst/N84_1 )
  );
  \$_NOT_  \uart_tx_inst/s_axis_tready_reg_inv_vname  (
    .A(nt_s_axis_tready),
    .Y(\uart_tx_inst/s_axis_tready_reg_inv )
  );
  \$_NOT_  \uart_tx_inst/s_axis_tvalid_inv_vname  (
    .A(nt_s_axis_tvalid),
    .Y(\uart_tx_inst/s_axis_tvalid_inv )
  );
  GTP_DFF_SE #(
    .GRS_EN("TRUE"),
    .INIT(1'h1)
  ) \uart_tx_inst/txd_reg  (
    .CE(\uart_tx_inst/N107_1 ),
    .CLK(nt_clk),
    .D(\uart_tx_inst/N111 ),
    .Q(nt_txd),
    .S(\uart_tx_inst/N109 )
  );
  \$_OR_  \uart_tx_inst/txd_reg_ce_fix  (
    .A(\uart_tx_inst/N107 ),
    .B(\uart_tx_inst/N109 ),
    .Y(\uart_tx_inst/N107_1 )
  );
endmodule
